### DISCUSSION TITLE
Integrating lambdas with existing VPC/Subnets

### DISCUSSION THREAD

**Discussion by mattguidone** [serverless-nextjs/serverless-next.js#2168] [Q&A] [answered]
I was reading on the Serverless documents a method for attaching pre-existing VPC's to lambdas like so:

```yaml
# serverless.yml
service: service-name
provider:
  name: aws
  vpc:
    securityGroupIds:
      - securityGroupId1
      - securityGroupId2
    subnetIds:
      - subnetId1
      - subnetId2

functions:
  hello: # this function will overwrite the service level vpc config above
    handler: handler.hello
    vpc:
      securityGroupIds:
        - securityGroupId1
        - securityGroupId2
      subnetIds:
        - subnetId1
        - subnetId2
  users: # this function will inherit the service level vpc config above
    handler: handler.users
```

Is it possible to specify and attach the lambdas that are generated from serverless-nextjs to a specific VPC and subnets? 

**EDIT**

It's currently not possible to associate Lambda@Edge with a VPC. Better luck next time
