### DISCUSSION TITLE
So many lambda functions after deploying

### DISCUSSION THREAD

**Discussion by Toshimichi0915** [serverless-nextjs/serverless-next.js#2469] [Q&A] [answered]
I've set up AWS CodeBuild to automatically deploy my website when master branch is updated. The problem is when the website is deployed new lambda functions are generated and old ones are not removed. How can I fix this issue?

I tried setting "inputs.name" but I got an error that says "Name cannot be specified across all Lambdas as it will cause conflicts."

serverless.yml
```yml
website:
  component: "@sls-next/serverless-component"
  inputs:
    bucketName: "website"
    cloudfront:
      distributionId: "website"
```

buildspec.yml
```yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run deploy
```

**Comment by Toshimichi0915** [comment, marked as answer]
```yml
  inputs:
    name:
      apiLambda: "sls-website-api"
      defaultLambda: "sls-website-default"
      imageLambda: "sls-website-image"
```
