### DISCUSSION TITLE
Customize pre-existing cloudfront

### DISCUSSION THREAD

**Discussion by McCo0L** [serverless-nextjs/serverless-next.js#2566] [Q&A]
We were able to customize a pre-existing cloudfront using sls-next/serverless-component using cloudfront as inputs for the component. Like this:

```
nextApp:
  component: "@sls-next/serverless-component"
  inputs:
  cloudfront:
    distributionId: IDIDIDIDID
    origins:
      - url: https://origin1.com
        protocolPolicy: https-only
        pathPatterns:
           whatever/origin1/*:
```

How can we change the response timeout parameter for that origin? it's defaulting to 30s.
