### ISSUE TITLE
CDK Construct - Support for outside hosted domain

### ISSUE THREAD

**Issue by haapti** [serverless-nextjs/serverless-next.js#1027]
**Is your feature request related to a problem? Please describe.**
Kind of. When the `hostedZone` is required im unable to use domain which is hosted outside of AWS (not in Route53).

**Describe the solution you'd like**

Setting only a certificate for a domain in AWS while DNS-hosting is outside of AWS.

```
const certificate = new Certificate(this, `Certificate-${id}`, {
	domainName: props.domain,
	validationMethod: ValidationMethod.DNS,
});

new NextJSLambdaEdge(this, `NextApp-${id}`, {
	serverlessBuildOutDir: './build',
	cachePolicyName: {
		staticsCache: `StaticsCache-${id}`,
		imageCache: `ImageCache-${id}`,
		lambdaCache: `LambdaCache-${id}`,
	},
	memory: 1024,
	name: {
		imageLambda: `ImageLambda-${id}`,
		defaultLambda: `DefaultLambda-${id}`,
		apiLambda: `ApiLambda-${id}`,
	},
	runtime: Runtime.NODEJS_12_X,
	timeout: Duration.seconds(30),
	withLogging: true,
	domain: {
		hostedZone: null,
		domainName: props.domain,
		certificate: Certificate.fromCertificateArn(
			this,
			`Certificate-${id}`,
			certificate.certificateArn.toString()
		),
	},
});
```

With serverless.yml you can do this like:

```
myNextApplication:
  component: serverless-next.js
  inputs:
    domain: ["foo.fuu.com"]
    cloudfront:
      defaults: # options for lambda that handle SSR
        forward:
          headers: [Host]
```
