### ISSUE TITLE
Failed to install serverless-component in bitbucket-pipelines with same config as before

### ISSUE THREAD

**Issue by dreamchests** [serverless-nextjs/serverless-next.js#1041]
### Describe the bug
First of all thanks to everyone who is maintaining this awesome repo!

Now to our bug: we are using bitbucket pipelines to automate deployment, the latest version of serverless and serverless-next.js. We did not change anything in our setting, however when running serverless, we are getting this error for the last few days:

```
Error: Command failed: npm install @sls-next/serverless-component@1.19.0 --prefix /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated acorn-import-meta@1.1.0: acorn>=7.2 supports import-meta
npm WARN deprecated acorn-export-ns-from@0.1.0: acorn>=7.2 supports export-ns-from
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated acorn-numeric-separator@0.3.6: acorn>=7.4 supports numeric separators
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module '/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN enoent ENOENT: no such file or directory, open '/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0/package.json'
npm WARN react-native-get-random-values@1.7.0 requires a peer of react-native@>=0.56 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-export-ns-from@0.1.0 requires a peer of acorn@^6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN @sls-next/serverless-component@1.19.0 No description
npm WARN @sls-next/serverless-component@1.19.0 No repository field.
npm WARN @sls-next/serverless-component@1.19.0 No README data
npm WARN @sls-next/serverless-component@1.19.0 No license field.
``` 

I analysed the differences to the previous builds. The last successful build and deploy ran 22 days ago using serverless@2.35.0, @sls-next/serverless-component@1.18.0 and node:12.21.0-alpine3.12. When running the same setup today, there this is the output of the serverless install:

```
npm install -g serverless@2.35.0

npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless.js
> snappy@6.3.5 install /usr/local/lib/node_modules/serverless/node_modules/snappy
> prebuild-install || node-gyp rebuild
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/serverless/node_modules/snappy/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.4.92-flatcar
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/serverless/node_modules/snappy
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> protobufjs@6.11.2 postinstall /usr/local/lib/node_modules/serverless/node_modules/protobufjs
> node scripts/postinstall

> aws-sdk@2.900.0 postinstall /usr/local/lib/node_modules/serverless/node_modules/aws-sdk
> node scripts/check-node-version.js

> serverless@2.35.0 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.3.5 (node_modules/serverless/node_modules/snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.3.5 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

serverless@2.35.0
added 603 packages from 422 contributors in 40.97s
```

This is the output of the last successful build for the same step:

```
npm install -g serverless

npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/serverless -> /usr/local/lib/node_modules/serverless/bin/serverless.js
/usr/local/bin/sls -> /usr/local/lib/node_modules/serverless/bin/serverless.js
> snappy@6.3.5 install /usr/local/lib/node_modules/serverless/node_modules/snappy
> prebuild-install || node-gyp rebuild
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/serverless/node_modules/snappy/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.4.92-flatcar
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/serverless/node_modules/snappy
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> protobufjs@6.10.2 postinstall /usr/local/lib/node_modules/serverless/node_modules/protobufjs
> node scripts/postinstall

> serverless@2.35.0 postinstall /usr/local/lib/node_modules/serverless
> node ./scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.3.5 (node_modules/serverless/node_modules/snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.3.5 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

serverless@2.35.0
added 605 packages from 424 contributors in 23.814s
```

I assume it is related to check-node-version, which was not shown previously, but I do not know where to look on how to fix it. I tried using the latest versions of all the packages and various combinations, however the error is the same. Looking forward to any hints or tips!

PS: 
Tried creating the specified missing dir using

```
mkdir -p /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0
``` 

(for that run using that version of serverless-component) as suggested by other issues with missing directories in this repo. Did not help unfortunately. 

### Actual behavior
The error above is displayed when running the pipeline. 

### Expected behavior
The pipeline should run as usual with the same settings.

### Steps to reproduce
Configuration to reproduce:

bitbucket-pipelines.yml:
```
image: node:12.21.0-alpine3.12

definitions:
    caches:
        nextcache: .next/cache
pipelines:
    branches:
        master:
            - step:
                  name: Master-Step Testing
                  image: circleci/node:12.7-browsers
                  deployment: testing
                  caches:
                      - node
                      - nextcache
                  script:
                      - npm install
                      - npm test
            - step:
                  name: Build and stage
                  deployment: staging
                  caches:
                      - node
                      - nextcache
                  script:
                      - apk add python3
                      - npm install -g serverless
                      - npm install
                      - npm run build
                      - export AWS_ACCESS_KEY_ID=$AWS_DEV_LAMBDA_KEY
                      - export AWS_SECRET_ACCESS_KEY=$AWS_DEV_LAMBDA_SECRET
                      - serverless --debug

```

serverless.yml:
```
someapp:
    component: "@sls-next/serverless-component@1.18.0"
    inputs:
        accelerated: false
        bucketName: somebucketname
        timeout: 30
        cloudfront:
            defaults:
                forward:
                    headers: [Host]
```

target: serverless :)

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 1.18.0, 1.19.0, latest builds (tried all the combinations to see where it fails)
- Next.js version: 10.0.3
- serverless: 2.32.1, 2.35.0, 2.36.0, 2.38.0, latest

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
