### ISSUE TITLE
Ability to set cache behavior for _next/image*

### ISSUE THREAD

**Issue by elliotcrawford** [serverless-nextjs/serverless-next.js#1045]
**Is your feature request related to a problem? Please describe.**
Hello! Is it possible to set custom values for the `_next/image*` CloudFront cache behavior?

I understand you can do:

```
myNextApplication:
  component: "@sls-next/serverless-component@{version_here}"
  inputs:
    cloudfront:
      distributionId: XYZEXAMPLE
      api:
        minTTL: 10
        maxTTL: 10
        defaultTTL: 10
      # you can set other cache behaviours like "defaults" above that can handle server side rendering
      # but more specific for a subset of your next.js pages
      /blog/*:
        minTTL: 1000
        maxTTL: 1000
        defaultTTL: 1000
        forward:
          cookies: "all"
          queryString: false
```

Is there an option to target `_next/image*`?

I've tried both `image` and `_next/image*` like so:

```
myNextApplication:
  component: "@sls-next/serverless-component"
  inputs:
    cloudfront:
      distributionId: XYZEXAMPLE
      image:
        forward:
          cookies: 'none'
```

```
myNextApplication:
  component: "@sls-next/serverless-component"
  inputs:
    cloudfront:
      distributionId: XYZEXAMPLE
      _next/image*:
        forward:
          cookies: 'none'
```
However both error out during the deploy with:

`Error: CloudFront input failed validation. Could not find next.js pages for "image"`
`Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"`

I can manually change the values in AWS however they get overwritten on subsequent deploys.

For reference I'm using `1.19.1-alpha.2`

Apologies if this is the wrong ticket type!

Thank you in advance
