### ISSUE TITLE
Command failed with Exit Code 1 - started happening two days ago

### ISSUE THREAD

**Issue by damianesteban** [serverless-nextjs/serverless-next.js#1102]
### Describe the bug
Up until two days ago the app never had an issue deploying. Now, I receive the following error:

```
sls

  error:
  Error: Command failed with exit code 1: node_modules/.bin/next build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/Users/damianesteban/src/betterpt/backend/serverless-deploy/yext-installer/node_modules/typeorm/platform'
```
### Actual behavior
Please see above

### Expected behavior
The app should deploy

### Steps to reproduce
Run `sls`

### Screenshots/Code/Logs

```

```myNextApplication:
  component: "@sls-next/serverless-component"
  inputs:
    domain: ["oauth", "example.net"]
    policy: "arn:aws:iam::XXXXXXXXXXX:policy/NextjsServerless"
```
### Versions

- OS/Environment: macOS Big Sur
- @sls-next/serverless-component version: most recent
- Next.js version: latest

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
