### ISSUE TITLE
Can't see logs of Lambda@Edge

### ISSUE THREAD

**Issue by KrustyC** [serverless-nextjs/serverless-next.js#1112]
### Describe the bug
I am trying to create a prototype using this package. My `serverless.yml` looks like this
```yml
todosDB:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: todos
    attributeDefinitions:
      - AttributeName: id
        AttributeType: S
    keySchema:
      - AttributeName: id
        KeyType: HASH
  region: us-east-1

dcrestiniMe:
  component: "@sls-next/serverless-component@1.19"
  inputs:
    build:
      env:
        DATABASE_URL: ${todosDB.name}
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
      imageLambda: "nodejs14.x"
    region: us-east-1
```
When I deploy, everything seems fine and I can access the default route which renders absolutely fine. The DynamoDB is also created with no problem. In my app though, I have implemented a small todos API, which has 2 routes, a GET `/api/todos` and a POST `api/todos/new`, as well as a page `/todos` which fetches the todos (I call the function rather than using the REST endpoint) and renders them. My problem is that this function is not working, as I get back 503. When I go onto AWS Lambda,  I can see the 3 lambdas being deployed and udpated but when I look at the logs to understand what's wrong, it looks as if none of those Lambda are invoked. I can not understand why no logs are appearing would anyone be able to help?

### Actual behavior

No logs are found in Cludwatch
### Expected behavior

I would expect to see some logs that could help debug wha'ts going on
### Versions

- OS/Environment: Mac OS Sierra (although this issue happen on the Lambda, not my laptop)
- @sls-next/serverless-component version: tested with `1.19.0` and `1.20.0-alpha.6`
- Next.js version: 10.2.0

### Additional context

I have a checked in every single region of AWS and I have not been able to find logs anywhere. In the Dashboard of Lambda I can see that something is being invoked, but when I use "go to logs" nothing shows up

![image](https://user-images.githubusercontent.com/20644593/119273293-15679b00-bc02-11eb-83ed-1a154eef4bef.png)

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
