### ISSUE TITLE
Support the new Serverless Components syntax

### ISSUE THREAD

**Issue by KrustyC** [serverless-nextjs/serverless-next.js#1113]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for the great plugin! I am trying to setup a todos app, to try out the component, and I am facing some issues with using the new syntax of Serverless Components. I am not sure when this syntax has ever been introduced, but it seems as if it's the new way to go with Serverless Components, as it also support dev mode and all the custom serverless commands, which are not supported with the old version.

**Describe the solution you'd like**
I would like to be able to use the new syntax, because as I mentioned above, it seems supported as well as more powerful. Would it be possible to be able to use this component with a syntax like the following?

```yml
component: "@sls-next/serverless-component"
name: my-website # The name of your Component Instance

inputs: # The configuration the Component accepts
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
```

**Describe alternatives you've considered**

**Additional context**
I am not sure whether you are currently planning this already or not, but I would also be happy to help if necessary and possible.
