### ISSUE TITLE
Auto-increment destinations of origin-request to latest version of lambda@edge

### ISSUE THREAD

**Issue by kamillle** [serverless-nextjs/serverless-next.js#1123]
**Is your feature request related to a problem? Please describe.**

I tried to modify forward cookie rules of cloudfront by serverless.yml. This way cannot autromatically update lambda@edgy version specified in cloudfront, we have to manually update the version by modifing the code.

```yaml
stage: production
nextamplified:
  component: "@sls-next/serverless-component@1.19.0"
  inputs:
    bucketName: sample
    roleArn: arn:aws:iam::000000000000:role/samlple
    build:
    cloudfront:
      origins:
        - url: http://sample.s3.us-east-1.amazonaws.com
          pathPatterns:
            _next/image*:
              minTTL: 0
              defaultTTL: 60
              maxTTL: 31536000
              forward:
                cookies: none
              lambda@edge:
                origin-request: arn:aws:lambda:us-east-1:000000000000:function:sample:1
```

**Describe the solution you'd like**

How about that serverless.yml accepts unqualified ARN of lambda and send qualified ARN that specifies the latest version of lambda to cloudfront.
