### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by gowtham2809** [serverless-nextjs/serverless-next.js#1218]
### Describe the bug
All the websites that are currently being hosted in serverless NextJS are facing open redirect vulnerability. Because of which it is causing unintended redirects to a different domain.

### Actual behavior
Here is one of my dev server that is currently hosted using Serverless NextJS (https://dev.insurepilot.de/)

When a user visits `https://dev.insurepilot.de//example.com/` redirects them to `example.com`

### Expected behavior
If any user visits that URL it should take them to the 404 pages.

### Steps to reproduce
1. If there is a slash at the end - `https://dev.insurepilot.de//example.com/` it redirects wrongly but if `https://dev.insurepilot.de//example.com` will result in a 404 page
2. This issue is happening only on the **home** page.

### Screenshots/Code/Logs
```
insurePilotWeb:
  component: '@sls-next/serverless-component@1.19.0-alpha.38'
  inputs:
    memory: 2048
    domain: ['dev', 'insurepilot.de']
    domainType: 'apex' 
    cloudfront:
      aliases: ['dev.insurepilot.de']
      comment: 'Dev Env'
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: 'arn:aws:acm:us-east-1:........'
    bucketName: '.....'
    bucketRegion: 'us-east-2'
    certificateArn: 'arn:aws:acm:us-east-1:......'
    enableHTTPCompression: true
    publicDirectoryCache:
      value: public, max-age=31104000
```

### Versions
- OS/Environment: Serverless Lambda
- @sls-next/serverless-component version: 1.19.0-alpha.38
- Next.js version: latest
