### ISSUE TITLE
domainRedirects wont update

### ISSUE THREAD

**Issue by Reiiya** [serverless-nextjs/serverless-next.js#1234]
### Describe the bug
adding domain redirects don't do the redirection

### Steps to reproduce
I used to have configuration like this:
```
myApp:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    domain: example.com
```
I followed docs and changed it to:
```
myApp:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    cloudfront:
      defaults:
        forward:
          headers: [Host]
    domain: ["example.com"]
    domainType: "both"
    domainRedirects:
      www.example.com: https://example.com
```
but redirection www to naked does not seem to work. Maybe there something I should manually remove for this to work out?

### Versions
- OS/Environment: Ubuntu
- @sls-next/serverless-component version: 1.19.0, 1.20.0-alpha.26
- Next.js version: 10.2.3

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
