### ISSUE TITLE
Custom Fonts 404 on server, 200 on localhost.

### ISSUE THREAD

**Issue by rapritchard** [serverless-nextjs/serverless-next.js#1316]
### Describe the bug
I am using some custom fonts that I have placed in `public/fonts`.

This all works fine on localhost, but as soon as it goes up to my server (not vercel, hosted on azure) the font files 404, despite other files such as JavaScript and favicons being found fine in the public folder.

### Actual behavior
Custom font files 404 on hosted server

### Expected behavior
Custom font files should be found and 200.

### Steps to reproduce
Include a custom font locally on a TypeScript project and push up to a server (not vercel, hosted on azure).

### Screenshots/Code/Logs
screenshot of the 404 errors:

_document.tsx
```javascript
import Document, { Html, Head, Main, NextScript, DocumentContext } from 'next/document';

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);

    return initialProps;
  }

  render() {
    return (
      <Html>
        <Head>
          <link
            rel="preload"
            href="/fonts/sofiapro-regular-webfont.woff2"
            as="font"
            crossOrigin=""
            type="font/woff2"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-regular-webfont.woff"
            as="font"
            crossOrigin=""
            type="font/woff"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-bold-webfont.woff2"
            as="font"
            crossOrigin=""
            type="font/woff2"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-bold-webfont.woff"
            as="font"
            crossOrigin=""
            type="font/woff"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;

```
global.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: 'SofiaPro';
  font-weight: 400;
  src: url('/fonts/sofiapro-regular-webfont.woff2') format('woff2'),
    url('/fonts/sofiapro-regular-webfont.woff') format('woff');
  font-display: swap;
}
@font-face {
  font-family: 'SofiaPro';
  font-weight: 700;
  src: url('/fonts/sofiapro-bold-webfont.woff2') format('woff2'),
    url('/fonts/sofiapro-bold-webfont.woff') format('woff');
  font-display: swap;
}


input:focus-within ~ label,
input:not(:placeholder-shown) ~ label {
  @apply transform scale-75 -translate-y-6;
}
```

### Versions
- OS/Environment: Windows
- Next.js version:  10.2.0,

### Checklist

- [x ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
