### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by justinwhall** [serverless-nextjs/serverless-next.js#138]
👋 looking to put a dev site behind basic auth. 

Worked though this by following this > https://medium.com/@Da_vidgf/http-basic-auth-with-api-gateway-and-serverless-5ae14ad0a270

Works great with the exception you need to manually attach the authorizer to each resource. This is, of course, not ideal as the site grows this needs to be manually attached with each route. 

There is an example on how to integrate these changes into the serverless framework. Now my issue is this plugin abastracts away the lamba config. ie:

```
handler: /path/to/page/handler.render
events:
  - http:
      path: pageName # home, about, etc. Unless is the index page which is served at /
      method: get
  - http:
      path: pageName # home, about, etc. Unless is the index page which is served at /
      method: head
```
https://github.com/davidgf/serverless-http-basic-auth/blob/master/serverless.yml

Is there a way to attach authorizer config to each resource?
