### ISSUE TITLE
404 Not Found with getServerSideProps

### ISSUE THREAD

**Issue by tranthaison1231** [serverless-nextjs/serverless-next.js#1444]
I follow https://www.serverless.com/plugins/serverless-nextjs-plugin this article to run project nextjs, i18next-next. But all good with getStaticProps, with getServerSideProps I have error This side not found in production

My configure serverless.yml
```
willink-web:
  component: '@sls-next/serverless-component@latest'
  inputs:
    minifyHandlers: true
    logLambdaExecutionTimes: true
    useServerlessTraceTarget: true
    build:
      postBuildCommands: ['node scripts/post-build.js']
    memory:
      defaultLambda: 1024
      apiLambda: 1024
      imageLambda: 1024
    runtime:
      defaultLambda: 'nodejs14.x'
      apiLambda: 'nodejs14.x'
      imageLambda: 'nodejs14.x'
    timeout:
      defaultLambda: 20
      apiLambda: 15
      imageLambda: 15
    name:
      defaultLambda: 'penrag8-el7ggmc'
      apiLambda: 'penrag8-el7ggmc'
      imageLambda: 'penrag8-el7ggmc'
    bucketName: 'penrag8-k5q73ne'
    cloudfront:
      #   # if you want to use an existing cloudfront distribution, provide it here
      distributionId: E3NNVQYBUILHBD
      # this is the default cache behaviour of the cloudfront distribution
      # the origin-request edge lambda associated to this cache behaviour does the pages server side rendering
      defaults:
        forward:
          headers:
            [
              CloudFront-Is-Desktop-Viewer,
              CloudFront-Is-Mobile-Viewer,
              CloudFront-Is-Tablet-Viewer,
            ]
      # this is the cache behaviour for next.js api pages
      api:
        minTTL: 10
        maxTTL: 10
        defaultTTL: 10
```
