### ISSUE TITLE
ISR - `name.regenerationLambda` custom input is not honoured

### ISSUE THREAD

**Issue by b3nThomas** [serverless-nextjs/serverless-next.js#1486]
### Issue Summary
Using a custom `regenerationLambda` name in `serverless.yml` is not supported and always uses the S3 bucket name.

I've picked through the code and can see the culprit here:
https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-component/src/component.ts#L576

There also doesn't appear to be any unit test coverage for capturing the `imageLambda` or `regenerationLambda` names as custom inputs:
https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-component/__tests__/custom-inputs.test.ts#L577-L582

### Actual behavior
The S3 bucket name is used for the `regenerationLambda` name, regardless of what custom input is supplied in `serverless.yml`.

### Expected behavior
When using the custom input `name.regenerationLambda` in `serverless.yml`, that name should be used when creating / updating the `regenerationLambda` in AWS.

### Steps to reproduce
- Use a custom `regenerationLambda` name in `serverless.yml`:
```
myApp:
    component: '@sls-next/serverless-component@3.1.0'
    inputs:
        bucketName: 'custom-cdn'
        name:
            apiLambda: custom-api
            defaultLambda: custom-default
            imageLambda: custom-image
            regenerationLambda: custom-regen <-----
```
- Run `serverless`.
- Check AWS > Lambda. Note that `regenerationLambda` is created using the S3 bucket name instead of `custom-regen`

### Screenshots/Code/Configuration/Logs
N/A

### Versions
- OS/Environment: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"`
- @sls-next/serverless-component version: `3.1.0`
- Next.js version:  `^10.2.3`

### Additional context
N/A

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
