### ISSUE TITLE
CloudFront tags not created with resource which causes permissions error when SCPs for tags on resources exist

### ISSUE THREAD

**Issue by Stetchy** [serverless-nextjs/serverless-next.js#1556]
### Issue Summary
Adding tags to the CloudFront configuration doesn't actually create the tags and attach them to the distribution at the time of the creation of the resource.

This is an issue when resources such as CloudFront distributions have Service Control Policies attached that assert specific tags must be on a resource.

### Actual behavior
Adding tags to the CloudFront configuration in the serverless.yaml does not actually create the tags at initial resource creation.

### Expected behavior
The tags specified in the config would be created and attached to the CloudFront distribution when it is created, not after creation.

### Steps to reproduce

Create a SCP that requires a specific tag on Cloudfront distributions at creation, like:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "DenyResourceCreationWithoutServiceTag",
      "Effect": "Deny",
      "Action": [
        "cloudfront:CreateDistribution",
      ],
      "Resource": "*",
      "Condition": {
        "Null": {
          "aws:RequestTag/someTag": "true"
        }
      }
    }
}
```

Using the below serverless.yaml or similar, run the `serverless` command to deploy your stack. 

### Screenshots/Code/Configuration/Logs

```yml
web:
  component: '@sls-next/serverless-component@v3.2.0'
  inputs:
    useServerlessTraceTarget: true
    domain: '<domain>'
    nextConfigDir: "./"
    bucketRegion: "eu-central-1"
    build:
      cleanupDotNext: false
      cmd: 'nx'
      args: ['run', 'build-serverless']
    certificateArn: "<arn>"
    cloudfront:
      webACLId: "<arn>"
      tags:
        Name: "name"
        service: "service"
        Environment: "dev"

```

### Versions

- OS/Environment: Alpine
- @sls-next/serverless-component version: 3.2.0
- Next.js version: 11.0.1

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
