### ISSUE TITLE
Add CloudFront Standard Logging Support

### ISSUE THREAD

**Issue by adamstirk-ct** [serverless-nextjs/serverless-next.js#1576]
**Is your feature request related to a problem? Please describe.**
To aid with troubleshooting and auditing I'd like the ability to be able to enable and configure CloudFront Standard Logging from within the serverless.yml configuration file.

**Describe the solution you'd like**
The following attributes to be supported under the CloudFront

```yaml
logging:
  bucket: 'myawslogbucket.s3.amazonaws.com.'
  includeCookies: false
  prefix: 'myfolder/'
```

For example

```yaml
WebApp:
  component: '@sls-next/serverless-component@latest'
  inputs:
    cloudfront:
      logging:
        bucket: 'myawslogbucket.s3.amazonaws.com.'
        includeCookies: false
        prefix: 'myfolder/'
```
These attributes should as per the CloudFormation documentation here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-logging.html

**Describe alternatives you've considered**
None
