### ISSUE TITLE
On getServerSideProps, 503 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by Sh031224** [serverless-nextjs/serverless-next.js#1646]
### Issue Summary

I get a 503 error on the page using getServerSideProps.

![image](https://user-images.githubusercontent.com/51149996/132320034-1b97db64-0c1c-4e20-91f0-712dbc24729c.png)

### Actual behavior

Other pages are displayed normally, but only the page using getServerSideProps throws an error.

### Expected behavior

Page is working

### Screenshots/Code/Configuration/Logs

```tsx
import { GetServerSideProps, NextPage } from "next";

const IndexPage: NextPage<any> = ({ test }) => {
  return (
    <>
      {test}
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: "test",
    },
  };
};

export default IndexPage;
```

```
stage: ${env.STAGE}
jampick-web:
  component: "@sls-next/serverless-component@3.3.0"
  inputs:
    useServerlessTraceTarget: false
    policy: arn:aws:iam::159698424543:policy/jampickweb-policy
    bucketName: jampickweb-${stage}
    buckerRegion: ap-northeast-2
    cloudfront:
      distributionId: ${env.${stage}_CLOUDFRONT}
    name:
      defaultLambda: jampickweb-default-lambda-${stage}
      apiLambda: jampickweb-api-lambda-${stage}
      imageLambda: jampickweb-image-lambda-${stage}

```

### Versions
Next.js 11.0.1
@sls-next/serverless-component 3.3.0

- OS/Environment: Mac 11.0.1
- @sls-next/serverless-component version: 3.3.0
- Next.js version: 11.0.1

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
