### ISSUE TITLE
Rewrite for /api routes not passing Auth header

### ISSUE THREAD

**Issue by arthur-cheung** [serverless-nextjs/serverless-next.js#1659]
### Issue Summary
This is very similar to [issue #863](https://github.com/serverless-nextjs/serverless-next.js/issues/863). I have the following re-write to an api gateway resource. 
```
async() => {
    return [
      {
        source: '/api/lambda/:path*',
        destination: 'https://<my-api-gateway-resource/:path*',
      },
    ]
  }
```
This resource uses cognito as an authorizer, so is expecting a bearer token in the auth header. This all works locally, it redirects fine to the api gateway resource, and I get 200.

I have kept the `/api/hello` endpoint to test, and that is fine. So the nextjs api is working fine.

I suspect the auth header isn't being parsed properly in the deployed lambda for some reason, but not sure how to debug this. Looking at the [rewriter code](https://github.com/serverless-nextjs/serverless-next.js/blob/v3.3.0/packages/libs/lambda-at-edge/src/routing/rewriter.ts#L53) it looks like it copies all the headers over.

### Actual behavior
I get 401 from `/api/lambda/:path` from the deployed endpoint.

### Expected behavior
200 and response from `api/lambda/path` from the deployed endpoint

### Versions
- OS/Environment: Deployed in AWS.
- @sls-next/serverless-component version: 3.3.0
- Next.js version: 11.1.2

### Checklist
- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Are you forwarding Authorization headers? Note that it is not forwarded by default (though it might make sense to do so in the future since headers like Authorization / Host are commonly used)

See: https://github.com/serverless-nextjs/serverless-next.js#custom-cloudfront-configuration

**Comment by arthur-cheung** [comment]
Thanks, I wasn't doing that. I have now added that. My yml now looks like:
```
service: moves-nextjs 

frameworkVersion: ">=1.2.0 <2.0.0"

playgroundMovesNextJs:
  component: "@sls-next/serverless-component@3.3.0"
  inputs:
    bucketName: <bucket-name>
    bucketRegion: ap-southeast-2
    cloudfront:
      distributionId: <cloudfront-distribution-id>
      aliases:  [<my domain>]
      certificate:
        iamCertificateId: <certificate-id>
      defaults:
        forward:
          headers: ["Authorization", "Host"]
```
I'm still getting 401s. Did it add it correctly? Or is there more I need to do?
