### ISSUE TITLE
My lambda must deployed to cn-northwest-1 in china. But it is always us-east-1?

### ISSUE THREAD

**Issue by hotlong** [serverless-nextjs/serverless-next.js#1686]
### Issue Summary

My lambda must deployed to cn-northwest-1 in china. But it is always us-east-1. aws key and secret in china can not apply to us-east-1 region: InvalidClientTokenId: The security token included in the request is invalid.

### Actual behavior

lambda deployed to us-east-1

### Expected behavior

lambda deployed to cn-northwest-1

### Steps to reproduce

```yml
# serverless.yml
myNextApplication:
  component: "./node_modules/@sls-next/serverless-component" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    name:
      defaultLambda: nextjsTestDefaultLambda
      apiLambda: nextjsTestApiLambda
      imageLambda: nextjsTestImageLambda
    domain: ["test", "steedos.cn"]
    stage: dev
    deploy: true
    bucketRegion: cn-northwest-1
    region: cn-northwest-1
    runtime: nodejs14.x
    memory: 2048
    timeout: 30
    enableS3Acceleration: false
```

### Screenshots/Code/Configuration/Logs

```
  DEBUG ─ Starting deployment of lambda nextjsTestApiLambda to the us-east-1 region.
  DEBUG ─ Syncing role v6excn-4asies in region us-east-1.

  error:
  InvalidClientTokenId: The security token included in the request is invalid.
```

### Versions

- OS/Environment: Mac
- @sls-next/serverless-component version: 3.3
- Next.js version: 11.1.2

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
