### ISSUE TITLE
roleArn doesn't work. serverless nextjs creates IAM role every time when deploying

### ISSUE THREAD

**Issue by s-kikuchi** [serverless-nextjs/serverless-next.js#1698]
### Issue Summary

I specify roleArn inside serverless.yml like below. However, somehow, serverless nextjs always create IAM role.

- serverless.yml

```
myApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.27"
  inputs: 
    roleArn: 'roleArn: "arn:aws:iam::123456789012:role/MyCustomLambdaRole"'
    :

```

### Actual behavior
Serveless nextjs creates IAM role every time when deploying.

### Expected behavior
Serveless nextjs doesn't create IAM role, just uses the IAM role I specify inside serverless.yml.

### Steps to reproduce
1. Specify IAM role inside serverless.yml
2. Deploy

### Screenshots/Code/Configuration/Logs
Nothing.

### Versions

- OS/Environment: on Github Actions
- @sls-next/serverless-component version: @sls-next/serverless-component@1.19.0-alpha.27
- Next.js version: 10.0.1

### Additional context
The content of IAM roles serverless nextjs always creates is this.

- Inline policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Resource": "*",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ]
        },
        {
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::hogehoge/*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ]
        }
    ]
}
```

- Trust relations

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "lambda.amazonaws.com",
          "edgelambda.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jchou1271** [comment]
+1 We're seeing the same thing.  It looks like it's creating a new role for each lambda (Default, API, Image), and so with each deployment, we see 3 new IAM roles created.

Versions:
- next:11.1.2
- sls-next `latest`
- Github Actions

**Comment by tornvallalexander** [comment]
Do we have any updated on this issue? Am struggling with the same thing

**Comment by erdemy** [comment]
Hi,
with the latest stable version v3.6.0, I got the following config:

```
myNextApplication:
  component: "@sls-next/serverless-component@v3.6.0"
  inputs:
    bucketName: ui-test
    roleArn: "arn:aws:iam::485300464508:role/service-role/nextjs-role-xxx"
    policy: "arn:aws:iam::485300464508:policy/service-role/AWSLambdaBasicExecutionRole-xxx"
```
it does not create IAM roles anymore.
