### ISSUE TITLE
cleanupDotEnv no longer works

### ISSUE THREAD

**Issue by dan-cooke** [serverless-nextjs/serverless-next.js#1718]
### Issue Summary
The `cleanupDotEnv` option has regressed since it was first released in 3.1.0-alpha.15. 

I stumbled upon this option while trying to debug the `build: false` command not behaving as I expected - the following issue https://github.com/serverless-nextjs/serverless-next.js/issues/1162

Solved my problems, but I had to downgrade to 3.1.0.alpha.15 to get the option to work.

### Reproduction
1. Create a `.next` directory - put anything in it, e.g a file called `test`
2. With the following `serverless.yml` run `serverless`
```yaml
app:
  component: "@sls-next/serverless-component@3.3.0" # latest
  build:
    cmd: true
    cleanupDotNext: false
```

### Actual behavior

The `.next` directory is cleared, and the `test` file is gone.

### Expected behavior

The `test` file sould remain

### Versions

Issue spotted in version 3.3.0.

Expected behaviour confirmed working in version 3.1.0-alpha.15, regression has happened somewhere between those.
