### ISSUE TITLE
Cannot prevent next build

### ISSUE THREAD

**Issue by dan-cooke** [serverless-nextjs/serverless-next.js#1719]
### Issue Summary

I am having tremendous difficulty getting this plugin to skip the `next build` step.

I have followed advice on this thread https://github.com/serverless-nextjs/serverless-next.js/issues/1162

To no avail.

### Steps to reproduce
```yml
  component: "@sls-next/serverless-component@3.2.0"
  build:
    # This is a weird one, but sls by default builds next with "next build"
    # we do not want this, so this option will just skip the next build
    cmd: true
    # Another issue with sls, is that it clears out the .next directory before
    # running. Our CI will build in an earlier step, so we do not want this
    cleanupDotNext: false
```

### Actual behavior

In a typescript nextJS project, that removes TS before deploying (as its only a development dependency) I get the following error

```
 Error: Command failed with exit code 1: node_modules/.bin/next build
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

```

### Expected behavior

When I run `serverless` I do not want this plugin to even talk to `next`. Or at least I want this to be configurable on my end, I would like to be able to specify the command that the build process uses.

### Additional context

It looks like the `cmd` is hardcoded in `lambda-at-edge` at this line https://github.com/serverless-nextjs/serverless-next.js/blob/3a11699f92df41ce9086fbc2f368ae21b2ac7252/packages/libs/lambda-at-edge/src/command.ts#L14

I would imagine this is just a default, I have not looked into it with much depth.

The stacktrace that calls `next build` seems to be centred around this module as well

```
async Builder.build (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.0/node_modules/@sls-next/lambda-at-edge/dist/build.js:359:13)
```
