### ISSUE TITLE
Index / Root Domain return a 404

### ISSUE THREAD

**Issue by spencermarx** [serverless-nextjs/serverless-next.js#1823]
### Issue Summary
The following example [NextJS repo](https://github.com/spencermarx/serverless-nextjs-404-issue) has been [deployed to AWS](https://dzagy7yjrvow2.cloudfront.net/) using the latest serverless-nextjs component. **Upon requesting the index/root domain**, a `404` is returned from Cloudfront, despite loading valid html from the response payload.

### Actual behavior

The root domain responds with a `404` http status code for the following [repo](https://github.com/spencermarx/serverless-nextjs-404-issue) / [deployed site](https://dzagy7yjrvow2.cloudfront.net/).

### Expected behavior
The index / root domain should respond with a valid `200` http status code in addition to the index.html.

### Steps to reproduce
1. Deploy the following [repo](https://github.com/spencermarx/serverless-nextjs-404-issue) to AWS by running...

```bash
$ npx serverless
```

2. Wait until the repo deploys successfully
3. Navigate to the cloudfront root url
4. Note that you are returned a `404` http status code, despite receiving valid html (which renders correctly to the page).

#### Headers

**General**
```
Request URL: https://dzagy7yjrvow2.cloudfront.net/
Request Method: GET
Status Code: 404 
Remote Address: 54.192.100.132:443
Referrer Policy: strict-origin-when-cross-origin
```

**Response**
```
age: 5
cache-control: public, max-age=0, s-maxage=2678400, must-revalidate
content-encoding: gzip
content-type: text/html
date: Tue, 12 Oct 2021 20:06:44 GMT
etag: W/"603327bcb5bc67e768d59edc5d860f86"
last-modified: Tue, 12 Oct 2021 20:01:04 GMT
server: AmazonS3
vary: Accept-Encoding
via: 1.1 1322f71561d45d48a5334ac75abd0c2f.cloudfront.net (CloudFront)
x-amz-cf-id: 6BCLIVQHrG9YQ9PYHG-ye2wGKT45WItHEFm9N45LlbXl3kpYd3K5Ig==
x-amz-cf-pop: EWR53-C3
x-cache: Error from cloudfront
x-edge-origin-shield-skipped: 0
```

**Request**
```
:authority: dzagy7yjrvow2.cloudfront.net
:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8
cache-control: no-cache
pragma: no-cache
sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
```

#### Serverless Config
```yml
# test
name: serverless-nextjs-404-issue

serverless-nextjs-404-issue:
  component: '@sls-next/serverless-component@3.4.0'
  inputs:
    domain: 'aclara.app'
    bucketName: serverless-nextjs-404-issue-s3
    description: '*lambda-type*@Edge for aclarify.com'
    build:
      postBuildCommands: ['node ./deploy/stages/post-build.js']
    name:
      defaultLambda: serverless-nextjs-404-issue-default-lambda
      apiLambda: serverless-nextjs-404-issue-api-lambda
      imageLambda: serverless-nextjs-404-issue-image-lambda
    runtime:
      defaultLambda: 'nodejs12.x'
      apiLambda: 'nodejs12.x'
      imageLambda: 'nodejs12.x'
    memory:
      defaultLambda: 2048
      apiLambda: 2048
      imageLambda: 2048
    timeout:
      defaultLambda: 30
      apiLambda: 30
      imageLambda: 30
```

#### manifest.json
```json
{"buildId":"PZFi394U44ONmB5aXmB2l","pages":{"dynamic":[],"ssr":{"dynamic":{},"nonDynamic":{"/_error":"pages/_error.js"}},"html":{"dynamic":{},"nonDynamic":{"/":"pages/index.html","/404":"pages/404.html"}},"ssg":{"dynamic":{},"nonDynamic":{},"notFound":{}}},"publicFiles":{"/.DS_Store":".DS_Store","/favicon.ico":"favicon.ico","/robots.txt":"robots.txt","/sitemap.xml":"sitemap.xml","/images/.DS_Store":"images/.DS_Store","/images/logo/icon.svg":"images/logo/icon.svg","/images/logo/logo.svg":"images/logo/logo.svg","/images/favicon/android-chrome-192x192.png":"images/favicon/android-chrome-192x192.png","/images/favicon/android-chrome-512x512.png":"images/favicon/android-chrome-512x512.png","/images/favicon/apple-touch-icon.png":"images/favicon/apple-touch-icon.png","/images/favicon/favicon-16x16.png":"images/favicon/favicon-16x16.png","/images/favicon/favicon-32x32.png":"images/favicon/favicon-32x32.png","/images/favicon/mstile-150x150.png":"images/favicon/mstile-150x150.png"},"trailingSlash":true,"domainRedirects":{},"hasApiPages":false,"enableHTTPCompression":false,"logLambdaExecutionTimes":false,"disableOriginResponseHandler":false}
```

#### routes-manifest.json
```json
{"version":3,"pages404":true,"basePath":"","redirects":[],"headers":[],"dynamicRoutes":[],"dataRoutes":[],"rewrites":[]}
```

#### Page View
<img width="1680" alt="Screen Shot 2021-10-12 at 4 29 24 PM" src="https://user-images.githubusercontent.com/39569555/137024670-15a58c55-d7ba-4453-920e-d4393587a47c.png">

### Versions
OS: `Mac OS Big Sur - 11.5 (20G71)`
NextJS: `11.0.1`

- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version:

### Additional context
* I am using Google Domains (where I purchased the domain) in tandem with Route53
