### ISSUE TITLE
Cannot find .serverless_nextjs/default-lambda/manifest.json

### ISSUE THREAD

**Issue by alirezavlz** [serverless-nextjs/serverless-next.js#2011]
### Issue Summary

Hello There, 
I'm trying to deploy my application using serverless-next.js but while running the `npx serverless` I get this error.
```
  error:
  [Error: ENOENT: no such file or directory, open '~~~~~~/.serverless_nextjs/default-lambda/manifest.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~~~~~/renderer/.serverless_nextjs/default-lambda/manifest.json'
```

### Screenshots/Code/Configuration/Logs

```
app:
  component: '@sls-next/serverless-component'
  inputs:
    distributionId: ***
    bucketName: ***
    nextConfigDir: ./renderer
    nextStaticDir: ./renderer
    memory: 1024
    build: false
    verbose: true
```
I build the app manually because of some additional configuration. 

### Versions

- OS/Environment: macOS
- @sls-next/serverless-component version: latest
- Next.js version: "^12.0.2"

### Checklist

- [ ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
