### ISSUE TITLE
Lamba functions are created in each deploy

### ISSUE THREAD

**Issue by CervarlCG** [serverless-nextjs/serverless-next.js#2059]
### Issue Summary

NextJS Serverless is creating 3 new functions (Image, API and Default) in each deploy instead of use the already created functions

### Actual behavior

3 new functions are created at each deploy

### Expected behavior
Use the 3 previous functions

### Steps to reproduce
Deploy a NextJS app with the next config
```
my-app:
  component: "@sls-next/serverless-component@3.5.3"
  inputs:
    useServerlessTraceTarget: true
    bucketName: xxxxxxxxxx
    cloudfront:
      distributionId: xxxxxxxxx
      comment: "My Application"
```
### Screenshots/Code/Configuration/Logs
![Screen Shot 2021-11-18 at 15 09 49](https://user-images.githubusercontent.com/53922412/142507379-c6f97399-c22b-4753-a621-8a7d4ec95e31.png)

### Versions

- OS/Environment: Ubuntu
- @sls-next/serverless-component version: 3.5.3
- Next.js version: 12
