### ISSUE TITLE
DynamoDB ResourceNotFoundException

### ISSUE THREAD

**Issue by LunarzFR** [serverless-nextjs/serverless-next.js#2115]
Hello,

I actually have a problem with the deployment of my application in production.
My DynamoDB table is in _eu-west-3_ region.

My serverless.yml configuration file :
```
myApp:
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    policy: 'arn:aws:iam::xxxxxxxxxxxx:policy/serverless'
```

Policy :
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

And my AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY user have the AdministratorAccess policy.

When I try to go to pages that use dynamodb in getServerSideProps I have this error :
```
{"message":"Requested resource not found","code":"ResourceNotFoundException","time":"2021-11-25T14:36:06.240Z","requestId":"xxxxx","statusCode":400,"retryable":false,"retryDelay":37.38152576541046}
```

I don't understand why I have this error because with the same configuration for dynamodb (region, table ...) in local it works. I hope someone have an idea to solve my issue ? I don't see what more I can do.
