### ISSUE TITLE
How to reference output values in another serverless template file

### ISSUE THREAD

**Issue by mjyocca** [serverless-nextjs/serverless-next.js#2146]
I'm somewhat new to serverless components and unsure how I would be able to dynamically reference the output values generated from this component, such as `appUrl` & `bucketName`. I see documentation mentioning being able to use the outputs for other components in the same file but my use case is I have a separate serverless file in another directory.

**nextjs/serverless.yml**
```
nextjsApp:
  component: '@sls-next/serverless-component'
  inputs:
    build:
      env:
      ...
  
resources:
  Outputs:
    AppUrl:
      Value: outputs.nextjsApp.appUrl
      Export:
        Name: appUrl
```

**backend/serverless.ts**
```ts
{
  ...
  'Fn::ImportValue': 'AppUrl'
}
```
