### ISSUE TITLE
Basic authentication screen is repeated

### ISSUE THREAD

**Issue by kodai305** [serverless-nextjs/serverless-next.js#2212]
I try to deploy next.js(SSG) to AWS. The template is below.

```
myApp:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    bucketName: "serverless-nextjs-mine-map"
    bucketRegion: "ap-northeast-1"
    enableHTTPCompression: true
    authentication:
      username: 'user'
      password: 'password'
    cloudfront:
      defaults:
        forward:
          queryString: false
          cookies: [ 'Auth' ]
          headers:
            [ 'Authorization' ]
```
### Issue Summary

I can deploy and the Basic authentication screen is displayed, but even if I authenticate, the Basic authentication screen is displayed many times.

### Actual behavior

Even if I authenticate, the Basic authentication screen is displayed many times.

### Expected behavior

If the authentication is successful, the Basic authentication screen disappears.

### Steps to reproduce

Executing the below command.
$ serverless

### Versions

- OS/Environment: MacOS 11.5.2
- @sls-next/serverless-component version: 3.6.0
- Next.js version: 12.0.3

### Checklist

- [ ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
