### ISSUE TITLE
TooManyOrigins: Your request contains more Origins than are allowed per distribution.

### ISSUE THREAD

**Issue by albehrens** [serverless-nextjs/serverless-next.js#2252]
My `serverless.yaml` file looks like this:

```
tasklistWeb:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    domain: "taskli.st"
    cloudfront:
      distributionId: E13UJ15VJIFQYO
```

Every time I deploy my application a new S3 bucket is created. That bucket is added as an origin to my CloudFront distribution with the fixed id of `E13UJ15VJIFQYO`. All of the traffic is redirected to the latest created S3 bucket. This is all great so far. 

The problem is however that the former S3 buckets with now obsolete application code do not get removed as origins from the distribution. There is a [quota](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-web-distributions) on a maximum of 25 origins per distribution. So after my 25th deployment my deployment pipeline breaks and I have to manually remove origins that point to outdated S3 buckets from my distribution.

How can I automatically delete older S3 buckets and remove them as origins from my CloudFront distribution?
