### ISSUE TITLE
CloudFront PriceClass cannot be set

### ISSUE THREAD

**Issue by matan3178** [serverless-nextjs/serverless-next.js#2263]
### Issue Summary
The PriceClass input of the CloudFront part in the serverless.yml is not actually being applied when deploying using `serverless` command.
I'm trying to set `priceClass: "PriceClass_100"` and it's not working

### Actual behavior
The actual PriceClass that applied is "PriceClass_ALL" 

### Expected behavior
Should be "PriceClass_100"

### Screenshots/Code/Configuration/Logs
My yaml file:
```
weddinvite_pages:
  component: "@sls-next/serverless-component"

inputs:
  cloudfront:
    distributionId: ***
    priceClass: "PriceClass_100"
    aliases: ["***"]
    certificate:
      cloudFrontDefaultCertificate: false 
      acmCertificateArn: "****"
```

### Versions
- OS/Environment: MAC
- @sls-next/serverless-component version: latest
- Next.js version: 12.0.7
