### ISSUE TITLE
Error: ENOENT: no such file or directory _app.js.nft.json/503 Cloudfront error

### ISSUE THREAD

**Issue by alirezavlz** [serverless-nextjs/serverless-next.js#2450]
```
"next": "^12.1.6"
```
serverless.yml
```
app-name:
  component: '@sls-next/serverless-component@3.3.0'
  inputs:
    useServerlessTraceTarget: true
   ****
```
next.config.js
```
  experimental: {
    outputStandalone: true
  },
```
### Issue Summary

503 Cloudfront errors, similar to #713 #819,
When I add `outputStandalone` it throws an error which is `Error: ENOENT: no such file or directory _app.js.nft.json` and when I removed it it deploys successfully but then I get 503 error.

logs
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '0' of undefined",
    "stack": [
        "TypeError: Cannot read property '0' of undefined",
        "    at Runtime.handler$1 [as handler] (/var/task/index.js:893:34)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```
Also I notice that even when I set the specific version to component (`@sls-next/serverless-component@3.3.0`) it still uses the 2.7.0,
