### ISSUE TITLE
Allow HTTP deployment

### ISSUE THREAD

**Issue by levansuper** [serverless-nextjs/serverless-next.js#2466]
**Is your feature request related to a problem? Please describe.**
I need to have a load balancer that will serve as a gateway for the multiple domains and redirect the traffic to the nextjs application.  While I was able to redirect the traffic but it works only if the cloudfront behaviours are set to HTTP and HTTPS. 

**Describe the solution you'd like**
Need to have an ability to make cloudfront behaviours  HTTP and HTTPS without changing the base configuration of the routes, or have an ability to extend these. 

for Example:
```
inputs:
    defaultBehavior: 
        viewerProtocolPolicy: "allow-all"
```

**Describe alternatives you've considered**
I tried using cloudfront but this only changes the default behavior:
```
cloudfront:
    defaults:
        viewerProtocolPolicy: "allow-all"
```
<img width="569" alt="Screenshot 2022-07-20 at 04 38 00" src="https://user-images.githubusercontent.com/223112/179871136-08357cbd-8980-4ae7-8854-815979cbf718.png">

**Comment by levansuper** [comment]
The answer was to add "allow-all" to all the routes
```    
  cloudfront
      defaults:
        viewerProtocolPolicy: "allow-all"
      _next/static/*:
        viewerProtocolPolicy: "allow-all"
      static/*:
        viewerProtocolPolicy: "allow-all"
      _next/data/*:
        viewerProtocolPolicy: "allow-all"

```
