### ISSUE TITLE
I can't deploy with Next v12.3.1 and @sls-next/serverless-component v3.7.0. CloudFront returns 503

### ISSUE THREAD

**Issue by TxusBlack** [serverless-nextjs/serverless-next.js#2498]
Hi everyone! Before we're using `"next": "^12.2.5"` but actually we need to use `"next": "^12.3.1",`, but when we deploy, the API returns an 503 error. I attach a picture of the error:

![image](https://user-images.githubusercontent.com/13071556/198078732-b4cdc439-4bb2-44ee-b0de-8745f5b6483b.png)

I also see the Cloudwatch Log and we have an error inside the library:

![image](https://user-images.githubusercontent.com/13071556/198078881-c92f6964-6592-4f06-9113-e990ce6290e8.png)

We're applying this solution, but how I explain, we need the version 12.3.1 for Next.js.

This is my serverless.yaml:

```
name: ...

nextApp:
  component: "@sls-next/serverless-component"
  inputs:
    # nextConfigDir: ../../
    aliases: ["..."]
    bucketName: "..."
    bucketRegion: "..."
    certificateArn: ...
    name:
      imageLambda: "..."
      defaultLambda: "..."
      apiLambda: "..."
    description: "..."
    runtime: "nodejs16.x"
    cloudfront:
      distributionId: "..."
      comment: '...'
    memory: 2048
    timeout: 30
    removeOldLambdaVersions: true
    build:
      args: ["build"]
      env:
        NEXT_PUBLIC_ENV: "production"
        AWS_ACCESS_KEY_ID: "..."
        AWS_SECRET_ACCESS_KEY: "..."
```

And for deploy I'm using:
`npx serverless@2.72.2`

Thank you!

- OS/Environment:
- @sls-next/serverless-component version: ^3.7.0
- Next.js version: ^12.3.1
- MacOS.
