### ISSUE TITLE
Will NextJS versions 13 and beyond receive support? If not, what alternatives will be available?

### ISSUE THREAD

**Issue by shivakantshukla55** [serverless-nextjs/serverless-next.js#2608]
**issue*
**`Next 14 Error: The "target" property is no longer supported in next.config.js`**

currently NextJs version: `14.1.3`

next.config.mjs
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
```

serverless.yml
```
NEXT-TEST:
  component: "@sls-next/serverless-component@3.6.0"  
  inputs:
    runtime:
      defaultLambda: "nodejs18.x"
      apiLambda: "nodejs18.x"
      imageLambda: "nodejs18.x"
    memory:
      defaultLambda: 4096
      apiLambda: 4096
      imageLambda: 4096
    timeout:
      defaultLambda: 30
      apiLambda: 30
      imageLambda: 30
  
    bucketRegion: XXXXX
    bucketName: XXXXXX
```

To deploy I am using below command: `npx serverless@2.72.2`

**Concern**
Can't use NextJs 12 now because most of things are now depricated.

**Question**

1. Will NextJS versions 13 and beyond receive support?
2. If not, what alternatives will be available?
