### ISSUE TITLE
[feature request] allow us to extend lambda roles

### ISSUE THREAD

**Issue by SarKurd** [serverless-nextjs/serverless-next.js#292]
Allow us to add roles to the lambdas since most organisation aws accounts has a very limited access

-----
Original issue:
I need to give it access to read secretsManager, i could only do it manually in AWS console, is there a way to do it in serverless yml or js file?

i need something like this
```
name: testAApp

appPortal:
  component: serverless-next.js
  inputs:
    domain:
      - ${env.subdomain}
      - ${env.domain}
    bucketName: ${env.bucketName}
    iamRoleStatements:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "arn:aws:secretsmanager:eu-central-1:<account_id>:secret:<secret_name>"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream,
            - logs:PutLogEvents
          Resource: "*"

```

I even tried to create a policy and added it to serverless.yml but still doesn't work

```
name: myapp

myAppPortal:
  component: serverless-next.js
  inputs:
    domain:
      - ${env.subdomain}
      - ${env.domain}
    bucketName: ${env.bucketName}
  	policy: "arn:aws:iam::930000340522:policy/myapp-limited-access"
```

### policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "arn:aws:secretsmanager:eu-central-1:930000340522:secret:myapp-v2-0vMKxR"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
```

### the only way i could make it work is finding the role this plugin creates and attach a policy to it

Appreciate some help here

**Comment by SarKurd** [comment]
Finally managed to get it work to deploy, now i have to work on the removing so you can run `sls remove`

@danielcondemarin could you please confirm if it's a good way to do it?

### serverless.js
```js
const yaml = require("js-yaml");
const fs = require("fs");
const aws = require("aws-sdk");
const { Component } = require("@serverless/core");

function addPolicy(policy) {
  const doc = yaml.safeLoad(fs.readFileSync("./serverless.yml", "utf8"));
  doc.myApp.inputs = {
    ...doc.name.inputs,
    policy
  };

  return doc;
}

class Deploy extends Component {
  async default() {
    const iam = new aws.IAM({ credentials: this.context.credentials.aws });
    const sts = new aws.STS({ credentials: this.context.credentials.aws });

    const params = {
      PolicyDocument: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: "secretsmanager:GetSecretValue",
            Resource: "*"
          },
          {
            Effect: "Allow",
            Action: ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            Resource: "*"
          }
        ]
      }),
      PolicyName: "myAppV2Policy",
      Description: "Policy used by myApp V2 website",
      Path: null
    };

    let policyArn = "";

    try {
      const identity = await sts.getCallerIdentity().promise();
      policyArn = `arn:aws:iam::${identity.UserId}:policy/myAppV2Policy`;

      await iam
        .deletePolicy({ PolicyArn: policyArn })
        .promise()
        .catch(err => err);
      await iam.createPolicy(params).promise();
    } catch (error) {
      throw new Error(error);
    }

    const doc = addPolicy(policyArn);

    const template = await this.load("@serverless/template");
    const output = await template({ template: doc });

    return output;
  }
}

module.exports = Deploy;

```

serverless.yml

```
name: my-app

myApp:
  component: serverless-next.js

```

**Comment by emiliedebra** [comment]
Is there a reason this was closed?

**Comment by SarKurd** [comment]
I didn't think Daniel would like to add this, i believe this will makes things much easier if they do.

I'll reopen it.

**Comment by danielcondemarin** [comment]
Have you checked https://github.com/danielcondemarin/serverless-next.js#aws-permissions ? You can add a policy input to the component: 

```yml
myNextApplication:
  component: serverless-next.js
  inputs:
    policy: "arn:aws:iam::123456789012:policy/MyCustomPolicy"
```
