### ISSUE TITLE
Code example error in readme

### ISSUE THREAD

**Issue by uclaeamsavino** [serverless-nextjs/serverless-next.js#343]
README is missing inputs: for custom build env example.

```
myNextApp:
  component: serverless-next.js
  build:
    args: ["build", "custom/path/to/pages"]
    env:
      DATABASE_URL: ${myDatabase.databaseUrl}
```

Should be:
```
myNextApp:
  component: serverless-next.js
  inputs: 
    build:
      args: ["build", "custom/path/to/pages"]
      env:
        DATABASE_URL: ${myDatabase.databaseUrl}
```
