### ISSUE TITLE
serverless returns 0 exit code when next build fails

### ISSUE THREAD

**Issue by cameron-martin** [serverless-nextjs/serverless-next.js#403]
**Describe the bug**
When the next.js build fails, the `serverless` cli still returns a zero exit code. This is particularly troublesome on CI, where the build output is read less frequently.

**To Reproduce**
1. Create a new next.js app.
2. Set up serverless-next.js with the following config:
```
foo:
  component: serverless-next.js
  inputs:
    build: false
    bucketName: foo
    domain: foo.com
```
3. Make a modification to the app to make the build fail, for example throw during SSR.
4. Run `serverless --component foo build`

**Expected behavior**
The command returns a non-zero exit code.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04, 19.10

**Additional context**
An example can be seen here: https://github.com/cameron-martin/tsumego/tree/f617a2b4e2bafda34fb6cfe7036e264b8380666f/packages/ui
