### ISSUE TITLE
How to setup 301 redirects

### ISSUE THREAD

**Issue by josephrequillart** [serverless-nextjs/serverless-next.js#417]
Hello,

Hi recently migrate my react app to next.js using this awesome repo for deploying it on my domain. I just have trouble to setup 301 redirects from my old blog (example.com/blog/post) to my new blog (blog.example.com/post).  

I would like to know what is the best way to setup 301 redirects in the cloufront distribution deployed with serverless-next. I found this interesting [aws blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/handling-redirectsedge-part1/) explaining how to use lambda@edge to setup redirects and I was wondering if there is a way to build something quite similar in our case? 

If this is not the best practice for this use case, do you guys have any idea for that?

Thanks a lot

**Comment by danielcondemarin** [comment]
@josephrequillart You should be able to do this by using your own custom cloudfront configuration. For example:

```
# serverless.yml
component: serverless-next.js@1.12.0-alpha.6
inputs:
  cloudfront:
    defaults:
       lambda@edge: # added to cloudfront default cache behavior
         viewer-request: arn:aws:lambda:us-east-1:123:function:lambdaWithRedirect:aVersion
```

Note that this is only available on the latest alpha version. Is not documented very well but happy to help you throw to get something working. Hopefully we can document an example under the [examples/](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-component/examples) folder.

**Comment by maddoxnelson** [comment]
I have been struggling with this exact problem for a couple weeks now, really pumped to hear there's a solution!

**Comment by josephrequillart** [comment]
@danielcondemarin it work perfectly fine! Thanks a lot for your awesome work.

**Comment by SarKurd** [comment]
@danielcondemarin would appreciate an example on how to configure next-offline, in the official nextjs example they use custom routes RFC https://github.com/zeit/next.js/issues/9081

Would love to help me rewrite the route for this example
https://github.com/zeit/next.js/blob/canary/examples/with-next-offline/next.config.js

Or @josephrequillart can share his configuration

**Comment by danielcondemarin** [comment]
@SarKurd I'm not familiar with the example but looks like you should be able to do the same as I suggested above. 
Rather than using the default cache behaviour, it would be more efficient to create a new cache behaviour for `/service-worker` path and define the `viewer-request` lambda for that only. However that's not supported at the moment. In future I will be adding first class support for rewrites but will wait until the api becomes stable in Next.js.

@josephrequillart I would really appreciate if you PR'ed an example of how you implemented this to the examples/ folder 🙂

**Comment by josephrequillart** [comment]
Here are the steps I followed to solve this issue.

- Deployed my next app using serverless-next
- Created a lambda in us-east-1 region (I did this directly in the aws console). Here is my index.js inspired from this [aws blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/handling-redirectsedge-part1/) :
```
'use strict';

exports.handler = (event, context, callback) => {
    
    let request = event.Records[0].cf.request;
    // Map your old urls to the new ones
    const urlMapping = {
      '/old/url' : '/new/url',
    }
    
    // if URI matches to 'old-url' then redirect to new uri  
    if(urlMapping[request.uri]){
      const redirectResponse = {
          status: '301',
          statusDescription: 'Moved Permanently',
          headers: {
            'location': [{
              key: 'Location',
              value: urlMapping[request.uri],
            }],
            'cache-control': [{
              key: 'Cache-Control',
              value: "max-age=3600"
            }],
          },
      };
      callback(null, redirectResponse);
  }
  else{
      // for all other requests proceed to fetch the resources
      callback(null, request);
  }
};
```
- Then attached trust relationship in IAM for my lambda function to allow lambda@edge deployment :
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "lambda.amazonaws.com",
          "edgelambda.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
- Deployed my lambda to Lambda@Edge, providing my distribution id and choosing viewer-request as the cloudfront event : 
![Capture d’écran 2020-05-27 à 15 16 41](https://user-images.githubusercontent.com/35463509/83023561-58ae1e80-a02d-11ea-85da-093e2bdc4e0d.png)

- Finally I added this to the serverless.yml of my next app but I am not entirely sure if it is useful:
```
# serverless.yml

my-next-app:
  component: serverless-next.js@1.12.0-alpha.6 // you need this version
  inputs:
    domain: ${env.domain}
    cloudfront:
      defaults:
        lambda@edge:
          viewer-request: arn:aws:lambda:us-east-1:123:function:lambdaWithRedirect:aVersion
```
Hope it helps.
If someone want to help me PR an example, it will be my pleasure to help but unfortunately I am new with serverless and I'm not able to deploy the viewer-request lambda directly from the serverless.yml script.

**Comment by SarKurd** [comment]
@josephrequillart thanks, i don't know how to create it in serverless components too. We can't use AWS console in production in our company, everything has to be coded, would appreciate if someone help

**Comment by medv** [comment]
We just have a monorepo of several services, one of which is this component and others use the vanilla serveress.yml syntax to deploy surrounding infrastructure (namely database migrations and scheduled data sync lambdas to fetch from external apis and update our databases). It's up to you how to orchestrate it all together, there are some solutions. For now I just deploy them in parallel in CI/CD.

It would be nice to see what serverless components v2 support brings and if it allows playing along with other serverless features in the same service definition, but I would have to assume there will always be this sort of rift with this component from the quick skimming I did. @danielcondemarin might be able to clarify?

**Comment by medv** [comment]
Thought I would include a very naive example using gitlab ci, I just had a quick hack on it yesterday so don't judge ;) 

.gitlab-ci.yml
```
image: node:12

stages:
  - deploy

include:
  - local: 'services/data/.gitlab-ci.yml'
  - local: 'services/front/.gitlab-ci.yml'
```

services/data/.gitlab-ci.yml
```
data-staging:
  stage: deploy
  only:
    refs:
      - staging
  cache:
    key:
      files:
        - services/data/package.json
        - services/data/package-lock.json
    paths:
      - services/data/node_modules/
  before_script:
    - npm config set prefix /usr/local
    - cd services/data
    - cat $ENV_DATA | tee .env # uploaded a env file to CI for this service & staging environment
    - npm install
    - npm install --only=development
  script:
    - ./node_modules/.bin/serverless deploy --stage staging --verbose
    - npm run migrate:up
  environment: staging

data-production:
  stage: deploy
  only:
    refs:
      - production
  cache:
    key:
      files:
        - services/data/package.json
        - services/data/package-lock.json
    paths:
      - services/data/node_modules/
  before_script:
    - npm config set prefix /usr/local
    - cd services/data
    - cat $ENV_DATA | tee .env # uploaded a env file to CI for this service & production environment
    - npm install
    - npm install --only=development
  script:
    - ./node_modules/.bin/serverless deploy --stage production --verbose
    - npm run migrate:up
  environment: production
```

services/front/gitlab-ci.yml
```
front-staging:
  stage: deploy
  only:
    refs:
      - staging
  cache:
    key:
      files:
        - services/front/package.json
        - services/front/package-lock.json
    paths:
      - services/front/node_modules/
  before_script:
    - npm config set prefix /usr/local
    - cd services/front
    - cat $ENV_FRONT | tee .env # uploaded a env file to CI for this service & staging environment
    - npm install
    - npm install --only=development
    - '[ ! -d "aws" ] && (curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip -o awscliv2.zip)'
    - './aws/install'
    - aws s3 sync s3://BUCKET_NAME/REPO_NAME/staging/.serverless .serverless --delete
  script:
    - ./node_modules/.bin/serverless
    - aws s3 sync .serverless s3://BUCKET_NAME/REPO_NAME/staging/.serverless --delete
  environment: staging

front-production:
  stage: deploy
  only:
    refs:
      - production
  cache:
    key:
      files:
        - services/front/package.json
        - services/front/package-lock.json
    paths:
      - services/front/node_modules/
      - services/front/aws/
  before_script:
    - npm config set prefix /usr/local
    - cd services/front
    - cat $ENV_FRONT | tee .env # uploaded a env file to CI for this service & production environment
    - npm install
    - npm install --only=development
    - '[ ! -d "aws" ] && (curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip -o awscliv2.zip)'
    - ./aws/install
    - aws s3 sync s3://BUCKET_NAME/REPO_NAME/staging/.serverless .serverless --delete
  script:
    - ./node_modules/.bin/serverless
    - aws s3 sync .serverless s3://BUCKET_NAME/REPO_NAME/staging/.serverless --delete
  environment: production
```
