### ISSUE TITLE
Getting 403 errors on some of the POST requests

### ISSUE THREAD

**Issue by pbteja1998** [serverless-nextjs/serverless-next.js#454]
**Describe the bug**
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: S9Bit4WZWnEar0Bo6NX7h-QbmHFUrnBF79lUp2LDYiLFoVPbw_bkTg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

I have suddenly started getting 403 error on some of the POST requests in my application.

My serverless.yml file for reference.
```
myNextApplication:
  component: serverless-next.js@1.14.0
  inputs:
    domain:
      - ${env.subdomain}
      - ${env.domain}
  build:
    cmd: yarn build
```
