### ISSUE TITLE
Question: Is there a way to add a resource policy without having to manually create it in AWS Console?

### ISSUE THREAD

**Issue by emiliedebra** [serverless-nextjs/serverless-next.js#458]
Versions used:
`serverless-next.js`: v1.15.0-alpha.0
`next`: v^9.4.0

I am wanting to restrict my serverless Next.js app by IP address on AWS.

Previously with `serverless-nextjs-plugin` you could simply add a resource policy in the `serverless.yml` like so:

```yml
provider:
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action:
        - execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp: // list of IPs
```

Is there a way to do this with `serverless-next.js component` without having to manually create the resource policy arn?

**Comment by emiliedebra** [comment]
As an FYI,
I have attempted to add another component into the `serverless.yml` as suggested here: https://github.com/danielcondemarin/serverless-next.js#my-component-doesnt-deploy
Such as:

```yml

myApp:
  component: serverless-next.js@1.15.0-alpha.0

MyIamRole:
  component: serverless/aws-iam-role
  name: my-iam-role-name
  inputs:
    policy:
      - Effect: Allow
        Principal: '*'
        Action:
          - execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          IpAddress:
            aws:SourceIp: [] // list of IPs
```

However I get the following error:
`Error: Component "serverless/aws-iam-role" was not found on NPM nor could it be resolved locally.`
I get a similar error for the example you put in the above link.

Further to this, the guidelines linked in the README for serverless components approach it in a slightly different way (https://www.serverless.com/blog/what-are-serverless-components-how-use/), in that there is a higher level `components` property,  under which the components are defined.
