### ISSUE TITLE
RFC - Using an existing CloudFront distribution

### ISSUE THREAD

**Issue by danielcondemarin** [serverless-nextjs/serverless-next.js#477]
### Problem

Currently you can’t reuse an existing CloudFront distribution when deploying your Next.js application with `serverless-next.js`
This is a pretty common use case for many users that need a single CloudFront distribution as a gateway to different applications (e.g. multiple Next.js frontends), proxies etc.

### Proposal

Add a new input to `serverless-next.js` to pass an existing distribution id:

```yml
myNextApp:
  component: "@sls-next/serverless-component@{version}"
  inputs:
     cloudfront:
       distributionId: EDFDVBD6EXAMPLE      
```

The given CloudFront distribution will be updated as outlined below:

The distribution’s default cache behaviour will have a Lambda@Edge function attached that will allow for server side rendering Next.js pages. The function will be invoked on origin-request events. See the AWS Docs for details on possible triggers.

Four cache behaviours will be added to the distribution:
- `/api/*` - This is for serving Next.js API requests. If the app doesn’t have any API pages then the cache behaviour won’t be added.
- `/_next/*` - This is necessary for Next.js client side assets.
- `/static/*` - This is necessary for user defined assets under the static/ folder.
- `_next/data/{BUILD_ID}/*` - This will be used to support Next.js static site generation improvements

The cache behaviors above are the same ones provisioned when a brand new distribution is created.
It’s important to note that these are reserved by `serverless-next.js and the existing cloudfront distribution should not have them already defined to avoid clashes.

#### Defining a different root path

If you need to host multiple Next.js apps under the same distribution then an optional root path can be provided:

```yml
myNextApp:
  component: "@sls-next/serverless-component@1.2.3"
  inputs:
    cloudfront:
       distributionId: EDFDVBD6EXAMPLE     
    rootPath: "/blog"
```

In this case `serverless-next.js` will attach the SSR Lambda@Edge function to a `/blog/*` cache behaviour rather than modifying the Default cache behaviour.

With this approach you could have multiple apps hosted under the same CloudFront distribution:

```yml
leadsApp:
  component: "@sls-next/serverless-component@1.2.3"
  inputs:
     cloudfront:
       distributionId: EDFDVBD6EXAMPLE     
     rootPath: "/leads"
```

```yml
customersApp:
  component: "@sls-next/serverless-component@1.2.3"
  inputs:
     cloudfront:
       distributionId: EDFDVBD6EXAMPLE     
     rootPath: "/customers"
```

```yml
blogApp:
  component: "@sls-next/serverless-component@1.2.3"
  inputs:
    cloudfront:
       distributionId: EDFDVBD6EXAMPLE     
    rootPath: "/blog"
```

This provides similar functionality to [Vercel's multi-zones](https://nextjs.org/docs/advanced-features/multi-zones)

Caveats

- Apps using the new `rootPath` feature won't be able to use [publicFiles](https://nextjs.org/docs/basic-features/static-file-serving) that are routed outside the root path, e.g. `/robots.txt`, `/manifest.json` etc. You would either have to manually manage this yourself or have a separate app that uses the default cache behaviour (i.e. doesn't use `rootPath`)
