### ISSUE TITLE
Can't pin the component's version in `serverless.yaml`

### ISSUE THREAD

**Issue by stephanschubert** [serverless-nextjs/serverless-next.js#489]
```sh
> sls

  error:
  Error: Component "serverless-next.js@1.14.0" was not found on NPM nor could it be resolved locally.
    at /Users/sschubert/git/hydra/packages/steve/node_modules/@serverless/core/src/utils/download.js:97:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

  0s › Template › Error: Component "serverless-next.js@1.14.0" was not found on NPM nor could it be resolved locally.
```

I tried installing it...

```sh
ll node_modules/serverless-next.js
total 864
drwxr-xr-x   14 sschubert  70120836   448B Jul  5 17:50 .
drwxr-xr-x  638 sschubert  70120836    20K Jul  5 17:50 ..
-rw-r--r--    1 sschubert  70120836    16K Jul  5 17:50 CHANGELOG.md
-rw-r--r--    1 sschubert  70120836   1.0K Jul  5 17:50 LICENSE
-rw-r--r--    1 sschubert  70120836    71B Jul  5 17:50 README.md
drwxr-xr-x    4 sschubert  70120836   128B Jul  5 17:50 __mocks__
-rw-r--r--    1 sschubert  70120836   156K Jul  5 17:50 arch.png
-rw-r--r--    1 sschubert  70120836    51K Jul  5 17:50 arch_no_grid.png
-rw-r--r--    1 sschubert  70120836   176B Jul  5 17:50 constants.js
drwxr-xr-x    4 sschubert  70120836   128B Jul  5 17:50 lib
-rw-r--r--    1 sschubert  70120836   171K Jul  5 17:50 logo.gif
drwxr-xr-x   15 sschubert  70120836   480B Jul  5 17:50 node_modules
-rw-r--r--    1 sschubert  70120836   2.7K Jul  5 17:50 package.json
-rw-r--r--    1 sschubert  70120836    14K Jul  5 17:50 serverless.js
```

My `serverless.yaml`:

```yaml
myApp:
  # it is recommended you pin the latest stable version of serverless-next.js
  component: serverless-next.js@1.14.0
  inputs:
    verbose: true
    build: false
```
