### ISSUE TITLE
Error: CloudFront input failed validation. Could not find next.js pages for "viewerCertificate"

### ISSUE THREAD

**Issue by promediacorp** [serverless-nextjs/serverless-next.js#491]
When attempting to add an ACM certificate to the CloudFront distribution, getting the error after deploying:

_Error: CloudFront input failed validation. Could not find next.js pages for "viewerCertificate"_

Here is the serverless.yaml:

```
myNextJSApp:
  component: "serverless-next.js@1.14.0"
  inputs:
    cloudfront:
      viewerCertificate: 
        - acmCertificateArn: "arn:aws:acm:us-east-1:xxxxxxxxxxxxx:certificate/xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxxxxxx"

```
I do see the cloudfront distribution updating in the console, but that cert does not get added in fails with the above message. 

The reason I am going down this route of trying to add the ACM cert (and CNAME), is because I want to point my A record from another AWS account to this distribution.

When I try to use go the input domain route, I get the message __Error: Domain was not found in your AWS account. Please purchase it from Route53 first then try again,_  since the domain is in a different AWS account. It seems like this wont work with a multi account organization for dev and prod, since it appears as the domain has to be in the same account as Cloudfront distribution.
