### ISSUE TITLE
Pass existing CloudFront Distribution ID to aws-cloudfront

### ISSUE THREAD

**Issue by danielcondemarin** [serverless-nextjs/serverless-next.js#492]
Currently the [aws-cloudfront](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/aws-cloudfront) component only supports creating new CloudFront distributions. 

In order to support the [RFC - Using an existing CloudFront distribution](https://github.com/serverless-nextjs/serverless-next.js/issues/477) aws-cloudfront would need to allow passing an existing distribution ID as [one of its inputs](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/aws-cloudfront#3-configure).

The following could be taken as acceptance criteria:

---------------------------------------------------

**Given an existing CloudFront Distribution ID 
New origins should be added (not override) to the CloudFront distribution.**

For example, take XYZEXAMPLE as an example distribution with one origin: https://example-origin.com. 

And the following `serverless.yml`

```yml
# serverless.yml
distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    distributionId: XYZEXAMPLE
    origins:
      - https://my-bucket.s3.amazonaws.com
```

The origin https://example-origin.com should be left intact and https://my-bucket.s3.amazonaws.com added.

---------------------------------------------------

**Given an existing CloudFront Distribution ID 
New custom cache behaviours should be added to existing origins**

Once again take XYZEXAMPLE as an example distribution with the origin: https://example-origin.com

And the following `serverless.yml`

```yml
# serverless.yml
distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    distributionId: XYZEXAMPLE
    origins:
      - url: https://my-bucket.s3.amazonaws.com
        pathPatterns:
            /sample/path:
              ttl: 10
              lambda@edge:
                viewer-request: arn:aws:lambda:us-east-1:123:function:myFunc:v1 # lambda ARN including version
```

The pathPattern (or cache behaviour in CloudFront terms) `/sample/path` is added to the distribution using as origin `https://my-bucket.s3.amazonaws.com`. Other cache behaviours using the origin should be left intact. 

**Implementation notes:**

To achieve the above you'll need to use [getDistributionConfig](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront.html#getDistributionConfig-property) to fetch the existing distribution configuration for merging it with the new inputs as explained above. 

Here is my attempt at starting implementing this a while back: 
https://github.com/danielcondemarin/aws-cloudfront/commit/150e1c59de04d7cc122608b2a415fb252441741e. 
Not much there but should give a rough idea on how to get started.
