### ISSUE TITLE
Can't successfully update deployment because sls gets stuck

### ISSUE THREAD

**Issue by thomasdissert** [serverless-nextjs/serverless-next.js#506]
**Describe the bug**

> Edit: This actually started with the error `Cannot find module '@sls-next/next-aws-cloudfront'` which I resolved by switching from version `'serverless-next.js@1.12.0-alpha.6'` to `'@sls-next/serverless-component@1.15.1'`.

I'm trying to update my deployment by running `sls --debug` and it inconsistently results in being stuck after the `Uploading ... lambda code` log line. Then it just continues to count the seconds as seen in the screenshot below.

My serverless.yml for that stage is in the `deployment/deployment_dev` directory and there are other deployment directories for the different stages for feature development. 

One of the serverless-files is the following (the other ones just differ by the values for different feature branch deployments):
```
dev:
  component: '@sls-next/serverless-component@1.15.1'
  stage: dev
  inputs:
    bucketName: dev
    name: dev
    nextConfigDir: ../../
```

**Things I've tried**
1. remove the `name` property, which is working for the other development stages, but not for the dev stage above
2. added `useServerlessTraceTarget: true` which causes a 503 Cloudfront error which comes down to a `Error: Cannot find module 'next/dist/next-server/server/node-polyfill-fetch'` in Cloudwatch.

**To Reproduce**

1. run `sls --debug` on an already deployed serverless instance

**Expected behavior**
The `sls --debug` command should successfully update the deployment or at least return an error why it isn't updating.
Also the `useServerlessTraceTarget: true` parameter shouldn't cause a MODULE_NOT_FOUND error. 

**Screenshots**
![Screenshot 2020-07-14 at 11 02 44](https://user-images.githubusercontent.com/11446531/87407333-4e86b600-c5c2-11ea-96ed-3f58539801f6.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.5
- Version: '@sls-next/serverless-component@1.15.1'

**Comment by thomasdissert** [comment]
Update: It looks like my problems are somehow connected to using `nextConfigDir`. I've now restructured my repository to sync the .serverless files into S3 and then wrote a serverless.yml using environment variables for different stages. That way it is working for me at least for now.

**Comment by teemuniiranen** [comment]
I am encountering the same with next.js 9.5.2 and @sls-next/serverless-component@1.16.0. I have environment specific configurations in ./sls/<environment>/serverless.yml and Iam refering to root with nextConfigDir: "../../".

Happens with useServerlessTraceTarget: true option but without I get the following error:
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation

**Comment by teemuniiranen** [comment]
@thomasdissert please reopen. This is still existing.

**Comment by thomasdissert** [comment]
As I've said, this is caused by the nextConfigDir setting. By removing it and then using environment variables and S3 sync like

```
user-portal:
  component: '@sls-next/serverless-component@1.15.1'
  stage: ${env.USERPORTAL_NAME}
  inputs:
    bucketName: ${env.USERPORTAL_NAME}
    name: ${env.USERPORTAL_NAME}
    useServerlessTraceTarget: true
    verbose: true
```

 I could fix my deployment.
