### ISSUE TITLE
How to set individual TTL times (Min TTL, Max TLL, Default TTL)?

### ISSUE THREAD

**Issue by mattdell** [serverless-nextjs/serverless-next.js#524]
Following the docs in the Readme there is a section about how to set the `ttl`

```
myNextApplication:
  component: serverless-next.js
  inputs:
    cloudfront:
      # this is the cache behaviour for next.js api pages
      api:
        ttl: 10
```

Cloudfront actually has the options for setting min, max, and default ttl times in the UI:

<img width="1080" alt="Screenshot 2020-07-27 at 13 10 17" src="https://user-images.githubusercontent.com/2536442/88540334-a2ee5480-d00a-11ea-8793-14abc71a015a.png">

How would I go about setting the Max TTL **only** to 31536000?

It seems this was supposed to be fixed in PR #282 since it enables "all cloudfront inputs" but these are missing. Looking through the code, it seems to be a limitation in [aws-cloudfront inputs](https://github.com/serverless-components/aws-cloudfront#3-configure)

See how it takes in `ttl` and then assigns that to min, max, and default? https://github.com/serverless-components/aws-cloudfront/blob/master/lib/getCacheBehavior.js

I have raised an issue there but it doesn't appear to be very active.

Does anyone else have this problem?

**Comment by medv** [comment]
Yeah this is relevant to us as well. I was meant to put some time into this when I have a chance but haven't had the opportunity yet. It's still on my list (that's currently still growing from the other end, ouchie)

**Comment by teemuniiranen** [comment]
I didn't understand from the documentation how to change these. I tried to change the default static files ttl:
```
nextApp:
    component: "serverless-next.js@1.9.5"
    inputs:
      nextConfigDir: "../../"
      bucketName: my-hostingbucket-develop
      cloudfront:
        origins:
          - url: /static
            pathPatterns:
              static/*:
                ttl: 600
```
