### ISSUE TITLE
CloudFront 502: The Lambda function returned invalid json: The json output is not parsable

### ISSUE THREAD

**Issue by ivanpetrushev** [serverless-nextjs/serverless-next.js#525]
**Describe the bug**
Hello, guys. 

The Default Lambda@Edge for the deployed distribution returns json that CloudFront does not understand.

**To Reproduce**
When I visit https://xxxxxx.cloudfront.net/page/home I get this output:

```
502 ERROR
The request could not be satisfied.
The Lambda function returned invalid json: The json output is not parsable. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

It is weird that CloudFront Monitoring for that Lambda reports 100% success rate.
If I go check the logs (in the edge region Lambda was executed for me), I can't see any errors. There is some output related to the page render process, and at the end I get the default:

2020-07-29T12:32:09.058+03:00 | END RequestId: xxxx-yyyy-zzzz
2020-07-29T12:32:09.058+03:00 | REPORT RequestId: xxxx-yyyy-zzzz	Duration: 7438.78 ms	Billed Duration: 7450 ms	Memory Size: 512 MB	Max Memory Used: 254 MB

**Additional context**
nextjs: 9.5.0 (also appears in 9.4.4)
serverless-component: 1.15.0-alpha.5 (also appears in 1.16.0-alpha.0)

serverless.yml:
```
prj:
  component: "@sls-next/serverless-component@1.15.0-alpha.5"
  inputs:
    bucketName: prj-xxx-dev
    bucketRegion: eu-central-1
    useServerlessTraceTarget: true
    build:
      env:
        NEXT_PUBLIC_PORTAL: prj-xxx
        NEXT_PUBLIC_HIDE_EXTRA_OUTPUT: true
        NEXT_PUBLIC_STORYBLOK_DEVMODE: false
```
