### ISSUE TITLE
Retrieving dynamic subdomain from request headers?

### ISSUE THREAD

**Issue by zhicong** [serverless-nextjs/serverless-next.js#537]
Hi, I've worked with Next.js but am new to Serverless, so huge props for enabling someone like me to deploy with Serverless so quickly!

My site serves content based on the subdomain. I am trying to extract the subdomain from the host in `req.header` in `getServerSideProps()`. However, it seems that the host is overridden to the S3 host instead. `req.headers.host` gives me `my-bucket.s3.amazonaws.com`, instead of `subdomain.mydomain.com`.

Unlike #434, my serverless.yml is the basic one as described in the README:
```
nextApp:
  component: "@sls-next/serverless-component@1.15.1"
  inputs:
    domain: ["*", "mydomain.com"]
    policy: ...
```

Is there a way to retrieve the dynamic subdomain when handling each request on the server side? Thanks!

**Comment by rodrigonehring** [comment]
Create a lambda with this code: (maybe: 'forward-host-edge')
```js
exports.handler = (event, context, callback) => {
    console.log(JSON.stringify(event, null, 2));
    const request = event.Records[0].cf.request;
    const eventType = event.Records[0].cf.config.eventType;
    const headers = request.headers;
    if (eventType === 'viewer-request') {
        const host = headers.host[0].value;
        const subdomain = host.split('.')[0];
        const domain = host.split('.')[1];
        headers['original-host'] = [{ key: 'original-host', value: host }];
    }
    //Return modified response
    callback(null, request);
};
```
Attach necessary policies and thrusted etc...
Then set custom cloudfront config in serverless.yml:

```yml
retail-page:
  component: '@sls-next/serverless-component@latest'
  inputs:
    cloudfront:
      defaults:
        lambda@edge:
          viewer-request: arn:aws:lambda:us-east-1:000000000000:function:forward-host-edge:VERSION
```

On next.js page:

```js
export async function getServerSideProps({ req }) {
  console.log('getServerSideProps', req)
  const host = req.headers['original-host']

  return {
    props: { host },
  }
}
```
