### ISSUE TITLE
Documentation about changing default TTL configuration for "static/*" is not clear enough

### ISSUE THREAD

**Issue by teemuniiranen** [serverless-nextjs/serverless-next.js#542]
I didn't understand from the documentation how to change the default TTLs for static files. I would like to change only the TTL for static path or even better to define sub path under static path to have a different value (for example /static/user to have lower TTL). I tried to change the default static files TTL this way:
```
nextApp:
    component: "@sls-next/serverless-component@1.17.0-alpha.16"
    inputs:
      bucketName: my-hostingbucket
      cloudfront:
        origins:
          - url: http://my-hostingbucket.s3.amazonaws.com.s3.us-east-1.amazonaws.com
            pathPatterns:
              static/*:
                minTTL: 600
                maxTTL: 600
                defaultTTL: 600
```
Can I define only the values I would like to change or do I need to then define the whole cloudfront configuration?

EDIT:
1. changed ttl settings to @sls-next/serverless-component@1.17.0-alpha.16 specific from generic one ttl parameter.
2. fixed the url parameter to include http://
