### ISSUE TITLE
Using serverless-next-js plugin and unable to set runtime to nodejs in pageConfig 

### ISSUE THREAD

**Issue by jessicachenfan** [serverless-nextjs/serverless-next.js#545]
**Describe the bug**
I'm using the serverless-next-js plugin in my serverless.yml file and I am trying to rewrite the runtime for the pages to nodejs since by default it is set to python ie:

```
provider:
  name: aws
  runtime: python3.8
  memorySize: 128
```
for reasons not related to this plugin. I am trying to rewrite the runtime like this:
```
custom:
  serverless-nextjs:
    pageConfig:
      "*":
        runtime: nodejs12.x
``` 

but I see that the runtime is still set to python for all the lambdas for the pages. 

**Expected behavior**
The runtime of the lambdas should be nodejs:

**Screenshots**
![image](https://user-images.githubusercontent.com/62560432/90284027-4333de00-de3f-11ea-92cc-800cbd0849c3.png)

You can see here that the runtimes are still set to python.

**Desktop (please complete the following information):**

- OS Catalina: 10.15.4

**Additional context**

**Comment by dphang** [comment]
I think you are using the old way (https://www.npmjs.com/package/serverless-nextjs-plugin) which is using vanilla Serverless Framework.

I used it briefly but don't remember that there's a way to set the runtime in the `custom` block. I think you need to update this block to:

```
provider:
  name: aws
  runtime: python3.8
  memorySize: 128
```

to

```
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
```

BTW, why not use the new way which is using Serverless components? I think the old way is deprecated now. Though `serverless.yml` is defined completely differently and you deploy with `serverless` instead of `serverless deploy`, you can refer to this readme for more info. You set the runtime this way, it was recently added: https://github.com/serverless-nextjs/serverless-next.js/commit/a0534ab7db8d4ebcdbad7719c16ad8eaee96eb71
