### ISSUE TITLE
Serverless.com dashboard not showing the component

### ISSUE THREAD

**Issue by MelMacaluso** [serverless-nextjs/serverless-next.js#563]
**Describe the bug**
All the scaffolding works nicely and the app is up and running as it should, unfortunately, the app does not show in the serverless.com dashboard (pardon if it is not meant to show, from my understanding it is).

**To Reproduce**

Our serverless.yml (stripped of everything so that is as barebones as it gets):

```yaml
msPortal:
  component: '@sls-next/serverless-component@1.17.0-alpha.6'
  inputs:
    name: msPortal
    bucketName: ms-portal-api-bucket
    runtime:
      defaultLambda: nodejs12.x
      apiLambda: nodejs12.x
    bucketRegion: eu-west-2
```
Our package.json looks like the following:

```json
{
  "name": "ms-portal",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "next-auth": "^3.1.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "postcss-flexbugs-fixes": "4.2.1",
    "postcss-preset-env": "^6.7.0",
    "tailwindcss": "^1.6.0"
  },
  "license": "MIT"
}
```

**Expected behavior**
From my understanding the app should be showing in serverless.com's dashboard so that we can monitor logging or configure CI/CD.
