### ISSUE TITLE
Mangaing dev and prod stages

### ISSUE THREAD

**Issue by BoazKG93** [serverless-nextjs/serverless-next.js#601]
Using the old serverless staging feature, I could easily manage and switch between stages (dev/prod). With the new configuration file, e.g.

```
treedis:
  component: "@sls-next/serverless-component@1.17.0-alpha.12"
  inputs:
    bucketName: "treedis-assets"
    bucketRegion: "us-east-1"
    name:
      defaultLambda: treedis-default-router
      apiLambda: treedis-api
```

I couldn't find any way to manage to different CloudFront distributions in the same serverless.yml file. I also didn't see anything in the documentation regarding this. This is extremely important, every single developer uses at least 2 environments, one for development and one for production. Without this feature this component wouldn't be usable as much.
