### ISSUE TITLE
Forward headers for API routes?

### ISSUE THREAD

**Issue by mrkstwrt** [serverless-nextjs/serverless-next.js#608]
**Is your feature request related to a problem? Please describe.**
It doesn't seem possible to add to the whitelist for headers for anything other than `defaults` which is then overridden by the `/api/*` rules.

For example with this config:

```yaml
inputs:
    cloudfront:
      /api/*:
        forward:
          headers: [ authorization ]
```

I get the error `Setting custom cache behaviour for api/ route "/api/*" is not supported`

**Describe the solution you'd like**
I want to be able to allow the `authorization` header to be passed up to my API routes, I can enable this by manually going into CloudFront and adding it to the whitelist, but this is overwritten every time I deploy so it's not really a workable solution when automating deployments. Or maybe I'm just doing it wrong.
