### ISSUE TITLE
How to configure multiple Alternate Domain Names (CNAMEs)

### ISSUE THREAD

**Issue by jjanssen** [serverless-nextjs/serverless-next.js#620]
I wasn't sure if this is the correct place for asking questions. So my apologies if this isn't the correct place. 

Coming from an AWS background I was wondering how I can configure the YAML file properly to handle multiple Alternate Domain Names (CNAMEs) for CloudFront aliasing? In addition I have been browsing through the codebase a little bit and on a domain level I see a configuration reference for domain and subdomains input, but in the current readme I only see a domain reference. 

For example I have the following configuration in my YAML:
```
my-website-acc:
  component: "@sls-next/serverless-component@1.16.0"
  inputs:
    domain: ["acc", "mywebsite.com"]
```

This creates a Route 53 record and sets it as a CNAME to the CloudFront distribution, but would it be possible to add additional aliases for eg: `acc2` and `acc3`?
