### ISSUE TITLE
Application always deploy to same cloudfront / s3 bucket even after changing stage!

### ISSUE THREAD

**Issue by super7egazi** [serverless-nextjs/serverless-next.js#645]
.Hi all,

My application always deploys to the same Cloudfront. This is my serverless.yml

```
myDomain:
  stage: prd
  component: "@sls-next/serverless-component@1.16.0"
  inputs:
    memory: 1024
```
The application deploys to a CloudFront distribution. Let's say I change stage to ```dev``` for instance, and it just deploys to the same CloudFront distribution of ```prd```
