### ISSUE TITLE
Is there a recommended cleanup procedure for accidentally-deleted .serverless directories?

### ISSUE THREAD

**Issue by NoelBaron** [serverless-nextjs/serverless-next.js#693]
### Describe the bug

- We began using `serverless-nextjs-plugin` w/ `serverless-domain-manager`.
- Before switching to `@sls-next`, a teammate deleted the `.serverless` directory and created a new `.serverless.yml` file.
- We removed all AWS resources associated with our `serverless-nextjs-plugin` experiment.
- Deploying with `@sls-next` yields `CNAMEAlreadyExists`.

### Actual behavior

- In CloudFront, the `CNAMES` column is empty. (Our distributions appear to be orphaned).
- Route53 does not have a record of the CNAME we specified.
- Our previously-generated Certificate does not show a relationship to the orphaned distributions.

### Expected behavior

- We expected SLS to determine CNAME viability by communicating with Route53, but it appears serverless is referencing its own state (which we have no ability to erase).
- We expected the CNAME column to propagate in CloudFront, but we assume the `CNAMEAlreadyExists` error is preventing that step from completion. 

### Screenshots/Code/Logs

```
service:
  name: redacted-dev
  component: "@sls-next/serverless-component@1.18.0-alpha.12"
  inputs: 
    bucketName: 'redacted-dev-serverless-assets'
    domain: ["dev", "redacted.com"]
    cloudfront:
      defaults:
        forward:
          headers: [Host]
 
app: redacted
org: redacted
```

### Versions

- OS/Environment: OSX 10.15.7
- @sls-next/serverless-component version: 1.18.0-alpha.12
- Next.js version: 9.5.5

### Additional context

We're hoping there is some sort of checklist we can run through to make sure our previous serverless state can be removed in order to make way for our new serverless state. 

### Checklist

- [x ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] Please first try using the latest `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
