### ISSUE TITLE
Cloudfront error 403

### ISSUE THREAD

**Issue by marcfielding1** [serverless-nextjs/serverless-next.js#775]
Hey Everyone,

For some reason I'm seeing static assets returning 403, please see screenshot below:

![image](https://user-images.githubusercontent.com/2651211/98359335-f74c9b80-201f-11eb-8495-73a0d6f43354.png)

My bucket access policy on s3 is: 

```
{
    "Version": "2012-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": " Grant a CloudFront Origin Identity access to support private content",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E1E4UFJ0D7LM6S"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::0lqnwy9-22lxsf/*"
        }
    ]
}
```

I was also reading another issue that suggested the Lambda execution role needed s3 access to, so I added s3Fullaccess (for now just to debug)

I also checked the cloudfront behavior points at the right bucket:

![image](https://user-images.githubusercontent.com/2651211/98360301-7bebe980-2021-11eb-9efe-bbdf6b09f7b4.png)

Any suggestions would be very helpful as I've been staring at this for hours!

I'm on serverless-next 1.18.0

**Comment by danielcondemarin** [comment]
Hey Mark, can you share your serverless.yml configuration as well please? Any custom inputs that might be causing this. 

Also, we grant the CloudFront distribution with access to S3 automatically. You shouldn't need to change anything for that to work.

**Comment by marcfielding1** [comment]
Hey Daniel!

Sure not touched anything really:

```
tths-ecommerce:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    domain: ["staging", "tothehighstreet.shop"]
    build:
      env:
        NODE_ENV: ${env.NODE_ENV}
```
