### ISSUE TITLE
Supplied policy not applying to lambdas.

### ISSUE THREAD

**Issue by Shadrack1701** [serverless-nextjs/serverless-next.js#782]
I am creating my AWS stack via terraform and supplying the distribution ID and policy ARN via env variables.  The distribution is working and being recognized correctly and my lambdas are being named correctly.  But it is always generating a new uniquely named role with the default inline policy instead of applying mine.  Is there something wrong with my serverless.yml?  

serverless.yml
```
name: "appName"
region: "us-east-1"
stage: "dev"

MyApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.3"
  inputs:
    bucketName: "${stage}-${name}-web-assets"
    bucketRegion: "${region}"
    cloudfront:
      distributionId: "WorkingDistributionID"
    name:
      defaultLambda: "${stage}-${name}-web"
      apiLambda: "${stage}-${name}-api"
    policy: "arn:aws:iam::123456789:policy/dev-app-web-logs-policy"
    nextConfigDir: "../"
```

The policy should have everything necessary for it to function and they are generating successfully.  Any help would be appreciated.

cloudfront.tf`
```
resource "aws_iam_policy" "dev-app-web-logs-policy" {
  name        = "dev-app-web-logs-policy"
  path        = "/"
  description = "Policy for Allowing Dev Website to write events to cloudwatch"

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents",
                "logs:GetLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}
```
