### ISSUE TITLE
Basic HTTP auth not working

### ISSUE THREAD

**Issue by katspaugh** [serverless-nextjs/serverless-next.js#785]
I'm trying to enable basic HTTP auth on our dev site and it doesn't seem to work.

Here's my `serverless.yml`:

```
webapp:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    enableHTTPCompression: true
    authentication:
      username: '***'
      password: '***'
    useServerlessTraceTarget: true
    domain: [ 'webapp', 'pizza' ]
    bucketName: 'webapp-pizza-static'
    nextStaticDir: ./public
    cloudfront:
      defaults:
        forward:
          queryString: false
          cookies: [ 'Auth' ]
          headers:
            [ 'Authorization' ]
```

Is the config correct?
