### ISSUE TITLE
503 Errors - The request could not be satisfied after adding cookie on getServerSideProps

### ISSUE THREAD

**Issue by hugomn** [serverless-nextjs/serverless-next.js#786]
### Describe the bug
I've recently started using Amplify SSR capabilities, which stores the auth session in a cookie that can be read in `getServerSideProps`.  The app is working fine locally, but after deploying using `serverless` I'm getting the `503 ERROR
The request could not be satisfied` error. 

I could not find any logs in my CloudFront monitoring or CloudWath tabs. Does anyone have any idea on how to find the log related to the error 503? How can I debug it? Any advice is highly appreciated.

### Actual behavior
I cannot access the app after deploying it with `serverless`. 

### Expected behavior
The app should be deployed with success.

### Screenshots/Code/Logs
<img width="817" alt="Screenshot 2020-11-11 at 22 18 42" src="https://user-images.githubusercontent.com/497957/98865563-dd6de700-246b-11eb-8962-ce5a94923b5d.png">

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 1.17.0
- Next.js version: 9.54

### Additional context
Here's my serverless.yml

```
myApp:
  component: '@sls-next/serverless-component@1.17.0'
  inputs:
    name: ${env.SUBDOMAIN}
    bucketName: web-${env.SUBDOMAIN}
    useServerlessTraceTarget: true
    domain:
      - '${env.SUBDOMAIN}'
      - 'myapp.dev'
```

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the latest `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by danielcondemarin** [comment]
> I could not find any logs in my CloudFront monitoring or CloudWath tabs. Does anyone have any idea on how to find the log related to the error 503? How can I debug it? Any advice is highly appreciated.

Because is Lambda@Edge you'll need to check the CloudWarch logs in the correct region, i.e. the region where the http request was made.

**Comment by hugomn** [comment]
Thanks @danielcondemarin! The only logs I find in my region don't have any errors. They are just normal requests:

<img width="1394" alt="Screenshot 2020-11-12 at 01 55 35" src="https://user-images.githubusercontent.com/497957/98881393-2a60b600-248a-11eb-8cd6-4f9cdca8b5b8.png">

Do I need to turn on any other logging to see the error? Can the 503 come from any other resource than the Lambda@Edge? Thanks!

**Comment by hugomn** [comment]
@danielcondemarin thanks for your reply. The answer was right in front of me: lambda had a timeout. I've just increased memory and timeout and it worked fine!

```
memory:
    defaultLambda: 2048
timeout:
    defaultLambda: 30
```
