### ISSUE TITLE
Can't pass env variables in gitlab environment to serverless

### ISSUE THREAD

**Issue by Reiiya** [serverless-nextjs/serverless-next.js#795]
### Describe the bug

I'm trying to wrap up serverless deployment of Next.js, however I can't get Gitlab env variables to work and get accepted by serverless. It accepts aws key and id fine, just none of the custom ones get taken into account.

### Screenshots/Code/Logs
Here is my serverless.yml
```
myNextApplication:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    domain: ${env.DOMAIN}
    name: ${env.APP_NAME}
    bucketName: ${env.APP_NAME}
    bucketRegion: ${env.AWS_BUCKET_REGION}
}
```
And my super simple .gitlab-ci.yml

```
stages:
  - deploy

deploy:
  stage: deploy
  image: node
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
  script:
    - >-
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      APP_NAME=$APP_NAME
      NODE_ENV=$NODE_ENV
      DOMAIN=$DOMAIN
      AWS_BUCKET_REGION=$AWS_BUCKET_REGION
      serverless
```

### Versions

- OS/Environment: Gitlab-CI runner
- @sls-next/serverless-component version: 1.18.0
- Next.js version: n/a
