### ISSUE TITLE
Allow custom domain using existing cert

### ISSUE THREAD

**Issue by jvarho** [serverless-nextjs/serverless-next.js#797]
**Is your feature request related to a problem? Please describe.**
The custom domain input only supports route 53 hosted domains. It would be great to support non-hosted domains, using either an existing cert from ACM (this proposal) or with a workflow that requests the cert and waits for validation.

**Describe the solution you'd like**
The simplest version of this feature could be something like:

```
  inputs:
    domain: my.domain.example.com
    certificate: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
The cert would have to already exist and match the domain name(s).

**Describe alternatives you've considered**
Alternatively, a new cert could be requested and wait for validation. More complex to implement, but simpler for the user.

**Additional context**
This is already possible manually, of course. First generate and validate the cert. Then modify the cloudfront distribution to add the cert and the alternative domain names. Not very robust. I'm not sure how well it survives major changes to the distribution, but at least tearing down and deploying again will require manual changes afterwards.

**Comment by dphang** [comment]
Did you try using the `certificate` and `aliases` CloudFront inputs? I added it exactly for this use case, since I manage my domains/certs outside of the component via Terraform (ACM certificate on AWS and domains on Cloudflare)

**Comment by Shadrack1701** [comment]
I was able to get around this by defining my CloudFront distribution in Terraform with the certificate assigned.  Then specifying the distribution in my serverless.yml.

Here is my serverless.yml for reference.
```
MyApp:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    bucketName: "${env.STAGE}-${name}-web-assets"
    bucketRegion: "${region}"
    **cloudfront:
      distributionId: "${env.DISTRIBUTION_ID}"**
    name:
      defaultLambda: "${env.STAGE}-${name}-web"
      apiLambda: "${env.STAGE}-${name}-api"
    policy: "${env.API_POLICY_ARN}"
    nextConfigDir: "../"
```

**Comment by jvarho** [comment]
@dphang Thanks! Yes, this worked:

```
  inputs:
    cloudfront:
      aliases: ['my.domain.example.com']
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: arn:aws:acm:us-east-1:...
```

I stopped reading the documentation after the custom domain section said only route 53 domains were supported. Might be a good idea to document this. Either way, works for me.
