### ISSUE TITLE
Error: Command failed with ENOENT: node_modules/.bin/next build

### ISSUE THREAD

**Issue by Shadrack1701** [serverless-nextjs/serverless-next.js#799]
When Running my build in my Github pipeline I can't get away from this error.  I've been searching everywhere, and tried tons of stuff to no avail.  Attached are the relevant files:

serverless.yml
```
myApp:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    bucketName: "${env.STAGE}-${name}-web-assets"
    bucketRegion: "${region}"
    cloudfront:
      distributionId: "${env.DISTRIBUTION_ID}"
    name:
      defaultLambda: "${env.STAGE}-${name}-web"
      apiLambda: "${env.STAGE}-${name}-api"
    policy: "${env.API_POLICY_ARN}"
    nextConfigDir: "../"
```

pipeline.yml
```
      - name: 'Install Dependencies'
        if: github.ref == 'refs/heads/master'
        working-directory: ''
        run: |
          npm ci
          ls -a
          cd node_modules/.bin
          ls -a

      - name: 'Build and Deploy Application'
        if: github.ref == 'refs/heads/master'
        working-directory: ''
        run: |
          echo "APPLICATION_SECRET=${{ secrets.DEV_APPLICATION_SECRET }}" >> .env
          echo "AUTH_COOKIE=${{ secrets.DEV_AUTH_COOKIE }}" >> .env
          echo "NODE_ENV=${{ secrets.DEV_NODE_ENV }}" >> .env
          cat .env
          npm run build
          env DISTRIBUTION_ID=$output_dist API_POLICY_ARN=$output_policy STAGE="dev" npx serverless
        env:
          APPLICATION_SECRET: ${{ secrets.DEV_APPLICATION_SECRET }}
          AUTH_COOKIE: ${{ secrets.DEV_AUTH_COOKIE }}
          NODE_ENV: ${{ secrets.DEV_NODE_ENV }}
```

As you can tell from my pipeline I'm checking my node_modules dir and 'next' is in there.  So I'm not sure if the serverless command is looking in the wrong directory perhaps?  Any help on this would be GREATLY appreciated.

Here is the detailed error that always occurs:
```
19s › myApp› Deploying 
aNA
  error:
  Error: Command failed with ENOENT: node_modules/.bin/next build
spawn node_modules/.bin/next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node_modules/.bin/next',
  path: 'node_modules/.bin/next',
  spawnargs: [ 'build' ],
  originalMessage: 'spawn node_modules/.bin/next ENOENT',
  shortMessage: 'Command failed with ENOENT: node_modules/.bin/next build\n' +
    'spawn node_modules/.bin/next ENOENT',
  command: 'node_modules/.bin/next build',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
25h
  20s › myApp › Error: Command failed with ENOENT: node_modules/.bin/next build
spawn node_modules/.bin/next ENOENT
```
