### ISSUE TITLE
Deploy wipes existing CloudFront behaviours

### ISSUE THREAD

**Issue by danturn** [serverless-nextjs/serverless-next.js#805]
We're looking to manage Cloudfront outside of serverless as we have multiple origins to support,

We're noticing that if we create cache behaviours in the AWS console and deploy they get wiped on deploy.

Is there any way to persist behaviours created outside of serverless?

**Comment by raffij** [comment]
I'm working with dan on this. Would you accept a pr if tested which persists the existing CacheBehaviors?

https://github.com/serverless-nextjs/serverless-next.js/compare/master...raffij:patch-1

**Comment by danielcondemarin** [comment]
Have you tried passing an existing distribution id?

```yml
# serverless.yml

myNextApplication:
  component: "@sls-next/serverless-component@{version_here}"
  inputs:
    cloudfront:
      # if you want to use an existing cloudfront distribution, provide it here
      distributionId: XYZEXAMPLE #optional
```

It was briefly documented here https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/serverless-components/aws-cloudfront#updating-an-existing-cloudfront-distribution
