### ISSUE TITLE
Adding serverless.yml parameters

### ISSUE THREAD

**Issue by AndreasLangberg** [serverless-nextjs/serverless-next.js#808]
Current serverless.yml file:

```
# serverless.yml

my-webclient:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    bucketName: my-webclient-bucket-development
    domain: ["development", "mypage.com"]
    build: 
      cmd: "yarn"
      args: ["build:development"]
```

There's a lot of hardcoded "development" in there. As with any project, I need to be able to create various environments for my deployments, yet I fail to find any way to actually do so. For something I could only imagine should be a simply thing, I have now looked through all the docs I could find and 4 pages of google search to no avail. Is there really no way to add a parameter to the `serverless` cmd line call which can be extracted in serverless.yml? Do I have to physically change out the entire file for every environment in the build step?
