### ISSUE TITLE
Multiple stages with Bitbucket Pipelines

### ISSUE THREAD

**Issue by 1nfinity-5starZ** [serverless-nextjs/serverless-next.js#810]
I've been struggling to deploy my app using Bitbucket Pipelines because I have multiple stages in the project (QA and PROD).

I wasn't able to find a solution for this in the issues or the documentation, there were a few examples that solved this problem of multiple stages using local deployment, but not trough the Bitbucket Pipeline.

The error is:

CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.

My serverless.yml:
```
landingPageApplication:
    component: "@sls-next/serverless-component@1.18.0"
    inputs:
        domain: ["qa-b2b", "afya.com.br"]
        build:
            env: 
                STAGE: 'QA'
```

My bitucket-pipelines.yml:
```
image: node:11.13.0-alpine
pipelines:
    branches:
      dev:
        - step:
            name: Init pipeline
            caches: 
              - node
            script:
              - echo "This step runs once you click the 'Run' button"
        - step:
            name: Deploy to QA
            trigger: manual
            deployment: qa
            image: node:11.13.0-alpine
            script:
              - apk add python3
              - npm install
              - npm install -g serverless
              - export AWS_REGION=sa-east-1
              - serverless config credentials --stage ${STAGE} --provider aws --key ${AWS_ACCESS_KEY_ID_QA} --secret ${AWS_SECRET_ACCESS_KEY_QA}
              - cp serverless.qa.yml serverless.yml
              - serverless --stage ${STAGE}
```

Any help would be appreciated.
