### ISSUE TITLE
cannot block all public access for the s3 bucket

### ISSUE THREAD

**Issue by nabsofken** [serverless-nextjs/serverless-next.js#813]
I am using the serverless next component and I have this setup
```    
nextJsUiApp:
  component: "@sls-next/serverless-component"
  inputs:
    bucketName: xxx
    bucketRegion: xxx
    domain: ["xxxx", "xxxxx.com"]
    nextConfigDir: "../../"
    cloudfront:
      # if you want to use an existing cloudfront distribution, provide it here
      distributionId: xxxxxx
      priceClass: "PriceClass_100"
      origins:
      - url: https://xxxx.s3.amazonaws.com
        private: true
```

setting the origin private flag to true doesn't seem to do anything to the bucket permissions or policy.

Can i block all public access through any of the config flags?
