### ISSUE TITLE
Cannot deploy via CI/CD - s3_static_assets_1.default is not a function

### ISSUE THREAD

**Issue by dustingraves** [serverless-nextjs/serverless-next.js#837]
### Describe the bug

When trying to use CI/CD with github actions I get an error about s3 bucket.

### Actual behavior

```shell
185s › sr-web › Deploying 
aNA
  185s › sr-web › Deploying 
aNA  DEBUG ─ Deploying bucket sr-web-test in region ***.
  DEBUG ─ Checking if bucket sr-web-test exists.

  185s › sr-web › Deploying .
aNA  DEBUG ─ Setting acceleration to "true" for bucket sr-web-test.
  DEBUG ─ Bucket sr-web-test was successfully deployed to the *** region.

  185s › sr-web › Deploying .
aNA
  185s › sr-web › Deploying ..
aNA
  error:
  TypeError: s3_static_assets_1.default is not a function
    at NextjsComponent.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.15.1/node_modules/@sls-next/serverless-component/dist/component.js:138:45)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.15.1/node_modules/@sls-next/serverless-component/dist/component.js:5:58)
25h
  185s › sr-web › TypeError: s3_static_assets_1.default is not a function

error Command failed with exit code 1.
25hinfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

### Expected behavior

Deployment should complete

### Steps to reproduce

deploy via github actions or possibly any ci/cd

### serverless.yml
```yaml
# serverless.yml

sr-web:
  component: "@sls-next/serverless-component@1.15.1"
  inputs:
    bucketName: sr-web-test
    memory: 512
    timeout: 30
    runtime: "nodejs12.x"
    useServerlessTraceTarget: true
    domain: ["web", "<DOMAIN>"] # [ sub-domain, domain ]
```
### config.next.js
```javascript
module.exports = {
  env: {
    ...
  }
}
```
### package.json snippet
```json
    "predeploy:test:infrastructure": "rimraf .env && node configure.js test && ./scripts/pre-test-deploy-notify.sh",
    "deploy:test:infrastructure": "sls --debug",
    "postdeploy:test:infrastructure": "node post.js test && ./scripts/test-deploy-notify.sh",
```

### Github actions file
```yaml
#github actions yaml
name: Continuous deploy Dev

on:
  push:
    branches: [dustingraves/ch33/setup-test-framework]

jobs:
  serverless-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

#     TODO: fix env file to be dynamic so test build can run
#      - name: Run Build
#        run: node_modules/.bin/next build

#      TODO: Can't run tests because we need to mock things
#      - name: Run tests
#        run: yarn test

      - name: Install Serverless Framework
        run: npm install -g serverless@1.67.0

        #TODO Change 'push' to 'merge'
      - name: Deploy to AWS
        if: "github.ref == 'refs/heads/dustingraves/ch33/setup-test-framework' && github.event_name == 'push'"
        run: 'yarn deploy:test:infrastructure'
```
### Versions

- OS/Environment: `x86_64 x86_64 x86_64 GNU/Linux`
- @sls-next/serverless-component version: `@sls-next/serverless-component@1.15.1`
- Next.js version: `"next": "9.4.4",`

### Additional context

When I upgrade to the latest serverless-component I get this issue: https://github.com/serverless-nextjs/serverless-next.js/issues/828

### Checklist

- [x ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
