### ISSUE TITLE
Static files cache behaviour

### ISSUE THREAD

**Issue by pecoram** [serverless-nextjs/serverless-next.js#852]
### Describe the bug
Hi,
I'm trying to add some cache for the static file /robots.txt placed inside the public folder via this configuration:
```
cloudfront:
   robots.txt:
        minTTL: 86400
        maxTTL: 86400
        defaultTTL: 86400
```
but I get this error:
Error: CloudFront input failed validation. Could not find next.js pages for "robots.txt"

Is it a bug or am I doing something wrong?

If I try to prepend a slash before path the file will be cached by default value (that in my case is 10 sec):

```
cloudfront:
   /robots.txt:
        minTTL: 86400
        maxTTL: 86400
        defaultTTL: 86400
```

### Versions

- OS/Environment: Linux
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.3

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
