### ISSUE TITLE
Getting 400 on Image Optimization

### ISSUE THREAD

**Issue by yasserf** [serverless-nextjs/serverless-next.js#857]
### Describe the bug

When using the `next/image` functionality with the serverless config:

```
  component: "@sls-next/serverless-component@1.19.0-alpha.21"
  inputs:
    imageOptimizer: true
    cloudfront:
      distributionId: XXXXX
      priceClass: "PriceClass_100"
      defaults:
        forward:
          headers: [Accept]
```

I get a 400 with the error:

```
"url" parameter is not allowed
```

Url looks like: 

`https://domain.com/_next/image?url=...&w=640&q=75`

### Expected behavior

To work the same way as locally / return a 200

### Steps to reproduce

I'm not doing anything special in terms of config, I have a fixed distribution id and using the lower tier cloudfront.

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 1.19.0-alpha.21
- Next.js version: 12
