### ISSUE TITLE
Pages with getServerSideProps always "Miss from cloudfront"

### ISSUE THREAD

**Issue by pecoram** [serverless-nextjs/serverless-next.js#862]
### Describe the bug
Hi,
pages with getServerSideProps always "Miss from cloudfront" instead pages with getInitialProps correctly give "Hit from cloudfront".

this is my default cache behaviour:
```
cloudfront:
      defaults:
        ttl: ${env.DEFAULT_BH_TTL}
        allowedHttpMethods: ['HEAD', 'GET']
        viewerProtocolPolicy: 'redirect-to-https'
        forward:
          headers: 'none'
          cookies: 'all'
          queryString: true
        lambda@edge:
          viewer-request: ${env.REWRITE_LAMBDA_ARN}
```

In the response there is:
```
Cache-Control: private, no-cache, no-store, max-age=0, must-revalidate
```
### Versions

- OS/Environment: Linux
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.3

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
