### ISSUE TITLE
Setup all default cloudfront behaviors (_next/* etc) to custom behaviors

### ISSUE THREAD

**Issue by FullOfOrange** [serverless-nextjs/serverless-next.js#875]
We need to use exist cloudfront and setup default behaviors to exist api gateway (not next-components) but, this module overwrite default behaviors and my custom behaviors every deployments. 

I try to use config below, but it always wipes out exist behaviors.
```yaml
app:
  component: "@sls-next/serverless-component"
  inputs:
    cloudfront:
      distributionId: EXAMPLE
```

Is there any way to handle this problems?

Thank you.
