### ISSUE TITLE
`sls remove` doesn't seem to tear down anything

### ISSUE THREAD

**Issue by iDVB** [serverless-nextjs/serverless-next.js#881]
### Describe the bug
I have an app using `@sls-next/serverless-component` deployed and working that I tried to tear down by running `serverless remove` in the same directory that it was deployed in.

### Actual behavior
![image](https://user-images.githubusercontent.com/189506/105241638-e3eb9f80-5b3b-11eb-9668-d3b43d6e7115.png)
However, all AWS resources are still deployed. Nothing torn down.

### Expected behavior
All AS resources should be torn down or deleted.

### Steps to reproduce
```
name: next-aws-lambda

website:
  component: '@sls-next/serverless-component@1.19.0-alpha.27'
  inputs:
    memory:
      defaultLambda: 1024
      apiLambda: 1024
    cloudfront:
      comment: 'next-aws-lambda (Managed by @sls-next/serverless-component)'
      /todoSSR/*:
        minTTL: 30
        maxTTL: 30
        defaultTTL: 30

```

### Versions
- OS/Environment:  **macOS 10.15.7**
- @sls-next/serverless-component version:  **1.19.0-alpha.27**
- Next.js version:  **10.0.5**
