### ISSUE TITLE
How to add custom environment variables to deployed application? Working with stages.

### ISSUE THREAD

**Issue by ratkorle** [serverless-nextjs/serverless-next.js#887]
Hi, 
I am sorry if this is already discussed or this isn't the place, but I can't find solution for my case, I hope someone will help.

So in my project I have one `.env` file on the **root** of the project, which has default environment variables for all stages.
Then I have `.env.staging` , `.env.production` etc.. and they are located in **separate config directory** .

When I run:
`env-cmd -f config/staging/.env.staging next build
`
and then: 
`next start`

It loads all the environment variables `.env` + `.env.staging`. Which is good and it works perfectly **but only locally**.

This is my **serverless.yml** file :
```
my-app-staging:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    nextConfigDir: ../../
    bucketName: my-app-staging
    cloudfront:
      comment: my-app-staging

```

So for staging deployment I run this:
`env-cmd -f config/staging/.env.staging next build && sls`

On the deployed version, All environment variables from root `.env` are available **but NOT** from `.env.staging`.

What I am doing wrong ?
