### ISSUE TITLE
Allow overriding of lambda@edge origin-request for custom paths

### ISSUE THREAD

**Issue by rdsedmundo** [serverless-nextjs/serverless-next.js#892]
**Is your feature request related to a problem? Please describe.**
I have a custom path on my NextJS app that I want to route through a custom Lambda@Edge function of my own, but [this code](https://github.com/serverless-nextjs/serverless-next.js/blob/828b9dde89a9cb2559c58ab4e798ee7cbcbdd5e6/packages/serverless-components/nextjs-component/src/component.ts#L647) overrides it even if I provide it in the input configuration.

**Describe the solution you'd like**
Allow the override to happen, I don't think it makes sense to have a configuration that gets overridden always.

**Describe alternatives you've considered**
Since I can't do this override I have to manually edit the `default-lambda` code using a custom script on the `build.postBuildCommands`.

**Additional context**
```
nextApp:
  component: '@sls-next/serverless-component@1.19.0-alpha.30'
  inputs:
    cloudfront:
      /custom-route/*:
        viewerProtocolPolicy: 'redirect-to-https'
        allowedHttpMethods:
          ['GET', 'HEAD', 'OPTIONS', 'PUT', 'POST', 'PATCH', 'DELETE']
        minTTL: 0
        maxTTL: 31536000
        defaultTTL: 0
        forward:
          cookies: 'all'
          queryString: true
        compress: true
        lambda@edge:
          origin-request: THIS_GETS_OVERRIDEN_WITH_THE_DEFAULT_LAMBDA_ARN
```
