### ISSUE TITLE
The files under the 'assets' not uploaded to S3

### ISSUE THREAD

**Issue by wondercise-wayne** [serverless-nextjs/serverless-next.js#932]
### Describe the bug
After building and deploying successfully through the `serverless` command, I found that S3 doesn't have all the files in the .**serverless_nextjs/assets** directory. Only the file BUILD_ID was uploaded, excluding the _next&public directory, and when I manually uploaded it to S3, all http requests returned 200 (otherwise it was 403).

### Actual behavior
Not all files uploaded to S3.

### Expected behavior
All files are correctly uploaded to S3

### Steps to reproduce

- Execute `cd config/staging && dotenv -e .env.staging serverless`.
- Deployed through serverless component.
- Check the difference between the local directory /.serverless_nextjs/assets/ and the file actually uploaded to S3.

### Screenshots/Code/Logs

serverless.yml (under /config/staging/ directory)
```
myWeb:
  component: "@sls-next/serverless-component@1.19.0-alpha.35"
  inputs: 
    build:
      postBuildCommands: ["cd ../../ && node post-build.js"]
    nextConfigDir: ../../
    domain: ["subdomain", "mydomain.com"]
    bucketName: mybucket
    bucketRegion: ap-northeast-1
    roleArn: "arn:aws:iam::1234567890:role/my-website-role"
    cloudfront:
        comment: "Website with Next.js deploy via serverless framework"
    name:
      defaultLambda: my-website-default-lambda
      apiLambda: my-website-api-lambda
      imageLambda: my-website-image-lambda
```
/.serverless_nextjs/assets/
![image](https://user-images.githubusercontent.com/80248105/110302325-15f58a00-8034-11eb-82b4-883d6fa468f0.png)

S3 Bucket
![image](https://user-images.githubusercontent.com/80248105/110302492-42a9a180-8034-11eb-9162-215a63b8e670.png)

Forbiddend access to static files
![image](https://user-images.githubusercontent.com/80248105/110302568-58b76200-8034-11eb-8daa-a26a97d60e74.png)

### Versions

- OS/Environment: Windows 10
- @sls-next/serverless-component version: 1.19.0-alpha.35
- Next.js version: 10.0.3

### Additional context

Use other versions (1.19.0-alpha.0) under the same settings without this problem, but this version doesn't seem to support custom roleArn.

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
