### ISSUE TITLE
The app is deployed but doesn't show up in my serverless.com dashboard

### ISSUE THREAD

**Issue by jeremygottfried** [serverless-nextjs/serverless-next.js#934]
### Describe the bug
Deployed App doesn't show up in my serverless.com dashboard.

Here's my serverless.yml
```yml
myApp:
  org: myOrg
  stage: prod
  component: "@sls-next/serverless-component@1.18.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    bucketName: myApp-nextjs
    region: us-east-1
    name: myApp
```

### Actual behavior
Serverless.com doesn't register a new app in my list of apps, even though the app is deployed

### Expected behavior
I see next app in my serverless.com dashboard
