### ISSUE TITLE
503 error with next-auth

### ISSUE THREAD

**Issue by jeremygottfried** [serverless-nextjs/serverless-next.js#935]
### Describe the bug
I am getting a 503 error with [next-auth](https://github.com/nextauthjs/next-auth) when I try to redirect to `/api/auth/signin`. I also get the same error if I try to load the signin page directly without a redirect.

> The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

![Screen Shot 2021-03-08 at 3 56 48 PM](https://user-images.githubusercontent.com/34523280/110381353-57336d00-8027-11eb-9237-3928f1cb812b.png)

Code:
```js
export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }
...
}
```

Serverless.yml:
```yml
myNextApp:
  org: myOrg
  stage: prod
  component: "@sls-next/serverless-component@1.18.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    bucketName: myApp-nextjs
    region: us-east-1
    name: myApp
```

### Actual behavior
Next-auth api endpoints are not working.

### Expected behavior
I expected the app to work the same way it does locally. I redirect to a signin page generated by next-auth when the user is not logged in.

Could be related to #819 or #222

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.
