### ISSUE TITLE
AccessDenied Error when using Next/Image

### ISSUE THREAD

**Issue by Shadrack1701** [serverless-nextjs/serverless-next.js#965]
### Describe the bug
I am trying to display an image using the next/image component so it loads faster.  
I can access the image navigating to it's url directly so it is available and loaded, it's something with the next/image 
 or lambda-image component.

### Actual behavior
On the page that displays the image it doesn't display, next/image returns `""url" parameter is valid but upstream response is invalid"` error from the endpoint `https://dev.cardscribed.com/_next/image?url=%2Fmascots.jpg&w=1920&q=75`.
Inside of the image lambda cloudwatch logs I am getting  `"ERROR Error processing upstream response (S3): AccessDenied: Access Denied"`

### Expected behavior
For the image to load correctly in the application when accessing `https://dev.cardscribed.com/_next/image?url=%2Fmascots.jpg&w=1920&q=75`.

### Steps to reproduce
You can navigate [here](https://dev.cardscribed.com/about) to see this error.  This is just a play site I am working on, but this is where the error can be seen.  
You can navigate [here](https://dev.cardscribed.com/mascots.jpg) to see the actual image is loaded correctly and available.

### Screenshots/Code/Logs
Here is my package.json dependencies:
```
  "dependencies": {
    "@hookform/resolvers": "1.3.0",
    "aws-sdk": "^2.853.0",
    "axios": "^0.21.1",
    "dayjs": "^1.10.4",
    "focus-trap-react": "^8.4.2",
    "jose": "^3.8.0",
    "nanoid": "^3.1.21",
    "next": "latest",
    "next-connect": "^0.10.0",
    "next-iron-session": "^4.1.12",
    "react": "^17.0.1",
    "react-async-hook": "^3.6.2",
    "react-dom": "^17.0.1",
    "react-hook-form": "^6.15.4",
    "react-virtual": "^2.5.0",
    "yup": "^0.32.9"
  }
```

Here is my serverless.yml:
```
CardScribed:
  component: "@sls-next/serverless-component@1.19.0-alpha.32"
  inputs:
    build:
      env:
        APPLICATION_SECRET: "${env.APPLICATION_SECRET}"
        ENV: "${env.ENV}"
    bucketName: "dev-cardscribed-next-app"
    bucketRegion: "${env.REGION}"
    cloudfront:
      distributionId: "${env.DISTRIBUTION_ID}"
    enableS3Acceleration: false
    name:
      apiLambda: "cardscribed-api"
      defaultLambda: "cardscribed-default"
      imageLambda: "cardscribed-image"
    roleArn: "${env.API_ROLE_ARN}"
```

In the aws console I can confirm the role being used by the imageLamda is: "dev-api-lambda-role".
dev-api-lambda-role:
    policy - dev-app-web-logs-policy:
```
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                  "logs:CreateLogGroup",
                  "logs:CreateLogStream",
                  "logs:DescribeLogStreams",
                  "logs:PutLogEvents",
                  "logs:GetLogEvents"
              ],
              "Resource": "*"
          }
      ]
  }
```
  policy - dev-app-api-policy:
```
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                  "s3:ListBucket",
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:DeleteObject"
              ],
              "Resource": [
                  "arn:aws:s3:::dev-cardscribed-storage",
                  "arn:aws:s3:::dev-cardscribed-emails",
                  "arn:aws:s3:::dev-cardscribed-next-app"
              ]
          },
          {
              "Effect": "Allow",
              "Action": [
                  "dynamodb:BatchGetItem",
                  "dynamodb:BatchWriteItem",
                  "dynamodb:DeleteItem",
                  "dynamodb:GetItem",
                  "dynamodb:GetRecords",
                  "dynamodb:PutItem",
                  "dynamodb:Query",
                  "dynamodb:Scan",
                  "dynamodb:UpdateItem"
              ],
              "Resource": "*"
          },
          {
              "Effect": "Allow",
              "Action": [
                  "logs:CreateLogGroup",
                  "logs:CreateLogStream",
                  "logs:DeleteLogGroup",
                  "logs:DeleteLogStream",
                  "logs:PutLogEvents"
              ],
              "Resource": "*"
          }
      ]
  }
```
The cloudfront distribution is pointed to s3 dev-cardscribed-next-app, which is where the application and static files are stored (as referenced in the serverless.yml).

### Additional context
It looks like everything should have access.  I'm not sure if I missed something obvious or there is an issue in the next/image component or possibly the image lambda.
The rest of the application and hosting works great, I really like the serverless-nextjs tool and have no complaints.  Just hoping someone else who has had the same/similar issues can help me out.  I spent three days on this trying things and I've run out of ideas.

Any help would be greatly appreciated!

Thanks!
Matt Trachsel

**EDIT entered wrong policy name for logging access**
